/**
 * Public contracts reviewed against SDK v0.8.0-alpha.8, commit
 * ea1ffc6ee68ffd650d1ceab5ca450ae0b8136434, rather than the current SDK sources.
 * Sources: kotlin/src/nimby/{NumberSetting,Mod,SignalModel,SignalTypes,
 * ModResources,ToolContext}.kt, the corresponding kotlin-client construction
 * API, and the construction/settings implementations shipped in that tag.
 */
export const alpha8Contracts: Record<string, [string, string]> = {
  'native:nimby:class:NumberSetting': [
    'Déclare un entier enregistré pour chaque signal, compris entre 0 et maximum inclus. maximum doit être compris entre 1 et 65535 ; defaultValue vaut 0 par défaut et doit être compris entre 0 et maximum inclus. Enregistrer le champ avec number dans son modèle, puis utiliser read(settings) dans les règles. visibleWhen commande sa présence dans le panneau ; il ne désactive pas à lui seul la règle qui utilise sa valeur.',
    'Declares an integer saved for each signal, from 0 through maximum inclusive. maximum must be between 1 and 65535; defaultValue is 0 unless specified and must fall within the value range. Register the field with number in its model, then use read(settings) in rules. visibleWhen controls its presence in the panel; it does not by itself disable the rule that uses its value.',
  ],
  'native:nimby:val:NumberSetting.name': [
    'Clé technique stable du champ, locale au type de signal et jamais traduite. Elle doit commencer par une lettre ASCII, puis contenir uniquement des lettres ASCII, des chiffres, des points, des tirets ou des traits de soulignement, sur 1 à 96 caractères. Les champs numériques d’un même type doivent avoir des noms distincts. Conserver ce nom entre versions pour retrouver les valeurs enregistrées.',
    'Stable technical field key, local to the signal type and never translated. It must start with an ASCII letter, followed only by ASCII letters, digits, dots, hyphens or underscores, for a total of 1 to 96 characters. Numeric fields within one type must have distinct names. Keep this name across versions to retain access to saved values.',
  ],
  'native:nimby:val:NumberSetting.label': [
    'Texte affiché à côté du champ entier. Il accepte tr(...) pour suivre la langue du jeu. La validation du modèle exige un libellé non blanc, sans caractère NUL et d’au plus 256 octets UTF-8. Ce texte peut évoluer sans renommer la clé name ni perdre les réglages enregistrés.',
    'Text displayed beside the integer field. It accepts tr(...) to follow the game language. Model validation requires a nonblank label, without NUL characters and no longer than 256 UTF-8 bytes. This text can change without renaming the name key or losing saved settings.',
  ],
  'native:nimby:val:NumberSetting.maximum': [
    'Borne supérieure incluse des valeurs du champ, comprise entre 1 et 65535. La borne inférieure est toujours 0 ; elle ne se configure pas. Le SDK ne donne pas de signification métier à 0 : le mod peut par exemple l’interpréter comme « ce signal seulement ». read ramène une valeur enregistrée hors plage à cette borne, tandis que withValue refuse une valeur hors plage.',
    'Inclusive upper bound of the field, between 1 and 65535. The lower bound is always 0 and cannot be configured. The SDK assigns no domain meaning to 0: a mod may, for example, interpret it as “this signal only”. read clamps an out-of-range stored value to this bound, whereas withValue rejects an out-of-range argument.',
  ],
  'native:nimby:val:NumberSetting.defaultValue': [
    'Valeur de repli, égale à 0 par défaut, qui doit être comprise entre 0 et maximum inclus. Elle est utilisée lorsque le champ n’a pas encore de valeur enregistrée. read complète aussi une représentation enregistrée incomplète avec les éléments de cette valeur par défaut ; il ne modifie ni la carte de réglages fournie ni la sauvegarde.',
    'Fallback value, 0 by default, which must be between 0 and maximum inclusive. It is used when the field has no saved value yet. read also completes an incomplete saved representation using the corresponding parts of this default; it changes neither the supplied settings map nor the save data.',
  ],
  'native:nimby:val:NumberSetting.visibleWhen': [
    'Nom exact d’une case déclarée dans le même modèle, ou chaîne vide par défaut pour un champ toujours visible. Ce n’est pas une expression. Le champ conditionnel apparaît immédiatement sous sa case ; plusieurs champs liés à la même case suivent leur ordre de déclaration. Les champs inconditionnels viennent après les cases. Masquer un champ conserve sa valeur enregistrée : les règles doivent encore vérifier la case si elles veulent ignorer cette valeur.',
    'Exact name of a checkbox declared in the same model, or an empty string by default for an always-visible field. This is not an expression. A conditional field appears immediately below its checkbox; several fields attached to the same checkbox follow declaration order. Unconditional fields come after the checkboxes. Hiding a field preserves its saved value: rules must still check the checkbox if they should ignore that value.',
  ],
  'native:nimby:fun:NumberSetting.read(Map<String,Boolean>)': [
    'Lit l’entier de ce champ dans la carte fournie et retourne toujours un Int compris entre 0 et maximum inclus, jamais null. Les éléments absents utilisent defaultValue ; une valeur décodée trop grande est ramenée à maximum. Cette lecture est sans écriture. Dans rules, fournir settings pour lire les réglages effectifs du signal, y compris ceux calculés par prepareNetwork pour cette évaluation.',
    'Reads this field from the supplied map and always returns an Int between 0 and maximum inclusive, never null. Missing parts use defaultValue; a decoded value above the bound is clamped to maximum. Reading performs no write. In rules, pass settings to read the signal’s effective settings, including values calculated by prepareNetwork for that evaluation.',
  ],
  'native:nimby:fun:NumberSetting.withValue(Map<String,Boolean>,Int)': [
    'Retourne une nouvelle carte contenant la valeur de ce champ et conservant les autres réglages de la carte d’entrée. value doit appartenir à 0..maximum inclus, sinon l’appel lève IllegalArgumentException. La carte d’origine reste inchangée. Cette fonction prépare des données pour une règle ou un test ; elle n’enregistre pas la valeur dans la partie et ne modifie pas le panneau du signal.',
    'Returns a new map containing this field’s value while preserving the input map’s other settings. value must be within 0..maximum inclusive, otherwise the call throws IllegalArgumentException. The original map is unchanged. This function prepares data for a rule or test; it does not save the value to the game or change the signal panel.',
  ],
  'native:nimby:class:SignalType': [
    'Décrit un type de signal avec une identité et un catalogue de textures stables, ses cases, ses actions et ses champs numériques persistants. numbers est vide par défaut et accepte au plus quatre champs aux noms distincts. construction vaut null par défaut : déclarer les ressources de construction pour obtenir l’entrée générée dans le jeu. Les noms de réglages sont locaux au type ; deux types peuvent déclarer des valeurs par défaut différentes pour un même nom.',
    'Describes a signal type with a stable identity and texture catalogue, its checkboxes, actions and persistent numeric fields. numbers is empty by default and accepts at most four fields with distinct names. construction defaults to null: declare construction resources to obtain the generated entry in the game. Setting names are local to a type; two types may declare different defaults for the same name.',
  ],
  'native:nimby:val:SignalType.checkboxes': [
    'Déclarations des réglages booléens de ce type, vides par défaut. Dans le modèle produit par le constructeur, cette liste contient aussi les déclarations nécessaires aux champs NumberSetting ; utiliser number et read plutôt que les manipuler soi-même. Les noms doivent être uniques et l’ensemble du type reste limité à 64 emplacements de réglages, partagés entre les cases ordinaires et les champs numériques. visibleWhen doit désigner une case déclarée du modèle.',
    'Boolean setting declarations for this type, empty by default. In the type produced by the model builder, this list also contains the declarations needed by NumberSetting fields; use number and read instead of manipulating those declarations yourself. Names must be unique and the type remains limited to 64 setting slots, shared by ordinary checkboxes and numeric fields. visibleWhen must name a declared checkbox in the model.',
  ],
  'native:nimby:val:SignalType.construction': [
    'Déclaration facultative des images et de l’entrée de construction, null par défaut. Le plugin Gradle s’en sert pour produire le paquet du jeu et vérifier les ressources. SignalConstruction permet notamment de choisir une taille de 0 à 4 et de demander la pose initiale à gauche. Ces préférences ne réécrivent pas les propriétés des signaux déjà placés ni celles conservées lors d’une copie de signal.',
    'Optional declaration of images and the construction entry, null by default. The Gradle plugin uses it to produce the game package and validate resources. SignalConstruction can select a size from 0 to 4 and request initial placement on the left. These preferences do not rewrite properties of existing signals or properties preserved when copying a signal.',
  ],
  'native:nimby:val:SignalType.numbers': [
    'Champs entiers persistants de ce type, dans leur ordre de déclaration ; la liste est vide par défaut. Au plus quatre champs sont autorisés, avec des noms distincts dans ce type. Les enregistrer avec SignalModelBuilder.number pour que les valeurs par défaut et la déclaration du modèle restent cohérentes. L’ordre visuel suit les cases liées par visibleWhen : chaque champ conditionnel vient sous sa case, puis les champs sans condition après les cases.',
    'Persistent integer fields for this type in declaration order; the list is empty by default. At most four fields are allowed, with distinct names within the type. Register them with SignalModelBuilder.number so that defaults and the model declaration stay consistent. Visual ordering follows the checkboxes referenced by visibleWhen: each conditional field is placed below its checkbox, then unconditional fields follow the checkboxes.',
  ],
  'native:nimby:class:SignalConstruction': [
    'Déclare les ressources et l’entrée de construction d’un signal. states contient de 1 à 256 chemins distincts, copiés dans leur ordre définitif ; ne pas retirer ni réordonner les images d’un catalogue publié. name est requis, kind vaut « path », catalogueName reprend name et les clés de localisation natives sont null par défaut. size vaut 0, avec des valeurs de 0 à 4 incluses ; left vaut false et true demande une pose initiale à gauche. Le plugin génère les fichiers du jeu et vérifie les images à la compilation.',
    'Declares a signal’s resources and construction entry. states contains 1 to 256 distinct paths, copied in their final order; do not remove or reorder images in a published catalogue. name is required, kind defaults to “path”, catalogueName defaults to name and native localisation keys default to null. size defaults to 0 and accepts 0 through 4 inclusive; left defaults to false and true requests initial placement on the left. The plugin generates game files and validates the images during the build.',
  ],
  'native:nimby:val:SignalConstruction.size': [
    'Taille initiale du signal dans le catalogue de construction du jeu, exprimée par son indice natif de 0 à 4 inclus, et non en mètres. La valeur par défaut est 0 ; une valeur hors plage est refusée dès la déclaration. Ce réglage ne redimensionne pas les signaux déjà présents. Une répétition conserve les propriétés du signal source au lieu de réappliquer la taille initiale du catalogue.',
    'Initial signal size in the game’s construction catalogue, expressed as its native size index from 0 through 4 inclusive, not in metres. The default is 0; an out-of-range value is rejected when declared. This setting does not resize existing signals. Repetition preserves the source signal’s properties instead of reapplying the catalogue’s initial size.',
  ],
  'native:nimby:val:SignalConstruction.left': [
    'Demande la pose à gauche des nouveaux signaux issus de cette entrée de construction, avec la même préférence dans l’aperçu et lors de la pose. false, valeur par défaut, conserve le comportement natif : il ne signifie pas « forcer à droite ». Le côté est distinct du sens de circulation. Cette préférence ne retourne pas les signaux existants et ne remplace pas le côté du signal source lors d’une répétition.',
    'Requests left-side placement for new signals created from this construction entry, using the same preference in the preview and during placement. false, the default, preserves native behaviour: it does not mean “force right”. Side is separate from running direction. This preference does not flip existing signals or replace the source signal’s side during repetition.',
  ],
  'native:nimby:val:SignalConstruction.states': [
    'Copie de la liste des images dans l’ordre du catalogue, avec 1 à 256 chemins distincts. Les chemins désignent les ressources du paquet ; dans la déclaration du modèle, assets/a.svg est fourni sous la forme a.svg. Le plugin vérifie les chemins et la présence des fichiers. L’ordre détermine l’identité des images dans les parties : conserver les anciennes entrées et leur position lorsqu’un catalogue a été publié.',
    'Copy of the image list in catalogue order, containing 1 to 256 distinct paths. Paths identify package resources; in the model declaration, assets/a.svg is supplied as a.svg. The plugin checks paths and file existence. Ordering determines image identity in saved games: retain existing entries and their positions once a catalogue has been published.',
  ],
  'native:nimby:fun:SignalModelBuilder.number(NumberSetting)': [
    'Ajoute un champ entier persistant au modèle et prépare les déclarations nécessaires à son enregistrement. Conserver l’objet NumberSetting pour appeler read(settings) dans les règles. La construction du modèle refuse plus de quatre champs, les noms numériques dupliqués et un visibleWhen non vide qui ne désigne aucune case du modèle. L’ordre des appels règle l’ordre entre champs attachés à la même case et entre champs inconditionnels.',
    'Adds a persistent integer field to the model and prepares the declarations needed to save it. Retain the NumberSetting object to call read(settings) in rules. Model construction rejects more than four fields, duplicate numeric names and a nonempty visibleWhen that does not identify a model checkbox. Call order determines ordering among fields attached to the same checkbox and among unconditional fields.',
  ],
  'native:nimby:fun:SignalModelBuilder.construction(List<String>,String,String,String,String?,String?,Int,Boolean)':
    [
      'Déclare les images et le signal constructible ; un nouvel appel remplace la déclaration précédente. states exige de 1 à 256 chemins distincts. name reprend le titre du modèle, kind vaut « path », catalogueName reprend name, les deux clés natives valent null, size vaut 0 et left vaut false par défaut. size accepte 0..4 inclus ; left = true demande les nouvelles poses à gauche. name et catalogueName acceptent tr(...), sans combiner tr avec une clé native pour le même texte. Le plugin produit les ressources du jeu sans exécuter les règles.',
      'Declares the images and constructible signal; another call replaces the previous declaration. states requires 1 to 256 distinct paths. name defaults to the model title, kind to “path”, catalogueName to name, both native keys to null, size to 0 and left to false. size accepts 0..4 inclusive; left = true requests new placement on the left. name and catalogueName accept tr(...), without combining tr and a native key for the same text. The plugin produces game resources without executing rules.',
    ],
  'native:nimby:fun:SignallingMod.prepareNetwork(List<Signal>)': [
    'Transforme les réglages effectifs de l’ensemble du réseau observé avant sa résolution ; par défaut, retourne la liste reçue. Le traitement doit rester pur et conserver le nombre, l’ordre, les identités, les types, les liens et les observations. Seuls les réglages peuvent changer, ainsi que le passage de SettingsStatus.Absent à Present lorsque des valeurs effectives sont fournies. Ces valeurs ne sont jamais enregistrées ni copiées comme préférences du signal. Un appel direct à evaluate ou decide ne déclenche pas cette préparation.',
    'Transforms effective settings across the observed network before it is resolved; by default, returns the input list. Processing must remain pure and preserve count, order, identities, types, links and observations. Only settings may change, together with a transition from SettingsStatus.Absent to Present when supplying effective values. These values are never saved or copied as signal preferences. Calling evaluate or decide directly does not run this preparation.',
  ],
  'native:nimby:fun:SignallingMod.prepareObservedNetwork(List<Signal>)': [
    'Valide puis prépare jusqu’à 512 signaux, y compris une liste vide. Les identités doivent être différentes de 0 et distinctes ; un type vide est remplacé par le premier type déclaré, un type inconnu est refusé. Après prepareNetwork, vérifie que l’ordre, les identités, les types, les liens et les observations sont conservés. Les réglages peuvent changer ; seul Absent → Present est autorisé comme changement de statut. Pour un signal Absent, utiliser Present avec des réglages dérivés, sinon le contexte de règle reprend les valeurs par défaut. Cette étape ne résout pas les liens manquants ni les cycles et n’écrit pas dans la sauvegarde.',
    'Validates and prepares up to 512 signals, including an empty list. Identities must be nonzero and distinct; an empty type is replaced by the first declared type, while an unknown type is rejected. After prepareNetwork, checks that order, identities, types, links and observations are preserved. Settings may change; Absent → Present is the only allowed status transition. For an Absent signal, use Present when supplying derived settings, otherwise the rule context uses declared defaults. This step neither resolves missing links or cycles nor writes to save data.',
  ],
  'native:nimby:fun:SignalModelsBuilder.prepareNetwork((List<Signal>)->List<Signal>)': [
    'Enregistre la préparation commune aux modèles assemblés par signalMod. Elle reçoit le réseau observé avant les règles et retourne une liste de même taille et dans le même ordre, en ne changeant que les réglages effectifs et, si nécessaire, Absent en Present. Elle ne persiste aucune valeur et ne rend jamais disponible un profil Unavailable. Sans déclaration, la liste est inchangée ; plusieurs appels remplacent le traitement précédent au lieu de les enchaîner. Utiliser evaluateNetwork dans les tests qui doivent inclure cette étape.',
    'Registers preparation shared by the models assembled with signalMod. It receives the observed network before rules and returns a list of the same size and order, changing only effective settings and, when needed, Absent to Present. It persists no values and never makes an Unavailable profile available. Without a declaration the list is unchanged; repeated calls replace the previous callback instead of chaining callbacks. Use evaluateNetwork in tests that need to include this step.',
  ],
  'native:nimby:fun:SignallingMod.evaluateNetwork(List<Signal>)': [
    'Retourne une décision par signal, dans l’ordre d’entrée, après la validation et la préparation de prepareObservedNetwork. La règle est d’abord appelée avec un voisin null ; une décision locale non nulle suffit sans résoudre le lien aval. Si elle demande le voisin, le SDK suit nextSignal puis réévalue en remontant le réseau. Un lien absent, un cycle nécessaire à la résolution ou une règle qui ne conclut toujours pas utilise invalidNetworkDecision du type concerné. Le parcours évite la récursion profonde et les réglages calculés ne sont pas enregistrés.',
    'Returns one decision per signal in input order after prepareObservedNetwork validates and prepares the network. A rule is first called with a null neighbour; a non-null local decision is sufficient without resolving the downstream link. If it needs the neighbour, the SDK follows nextSignal and then evaluates back through the network. A missing link, a cycle needed for resolution, or a rule that still cannot decide uses invalidNetworkDecision for the relevant type. Traversal avoids deep recursion and calculated settings are not saved.',
  ],
  'native:nimby:fun:validateSignalTypes(List<SignalType>)': [
    'Refuse une déclaration invalide par IllegalArgumentException : 1 à 16 types aux identifiants et catalogues distincts, approachBlocks de 1 à 16, actions valides et au plus quatre champs numériques de noms distincts par type. Chaque champ exige un libellé non blanc sans NUL d’au plus 256 octets UTF-8, une case visibleWhen existante si renseignée et des valeurs par défaut cohérentes. Les cases et champs numériques partagent 64 emplacements : un entier consomme le nombre nécessaire à sa plage, soit 7 pour maximum = 64 et 16 pour maximum = 65535. Le constructeur number s’occupe de ces déclarations. Cette validation n’exécute pas les règles et ne résout pas le réseau.',
    'Rejects invalid declarations with IllegalArgumentException: 1 to 16 types with distinct identities and catalogues, approachBlocks from 1 to 16, valid actions, and at most four numeric fields with distinct names per type. Each field requires a nonblank, NUL-free label of at most 256 UTF-8 bytes, an existing visibleWhen checkbox when specified, and consistent defaults. Checkboxes and numeric fields share 64 slots: an integer uses the number required by its range, namely 7 for maximum = 64 and 16 for maximum = 65535. The number builder prepares these declarations. Validation neither executes rules nor resolves the network.',
  ],
  'native:nimby:fun:ToolContext.showPanel(SignalActionRequest,String,List<ToolButton>,List<ToolNumberInput>)':
    [
      'Remplace uniquement l’action à l’origine de request par un message, jusqu’à 12 boutons et 4 champs entiers temporaires ; leurs identifiants doivent être distincts sur l’ensemble du panneau. La demande doit appartenir au monde et à la génération du contexte. Chaque texte est limité à 256 octets UTF-8, sans NUL, et chaque valeur entière doit respecter ses bornes inclusives. Les clics reviennent au même service avec l’identifiant du bouton dans action. Si la présentation est devenue périmée, par exemple après suppression du signal ou changement de catalogue, elle peut être ignorée sans exception ; le retour Unit ne prouve donc pas que le panneau est visible. Les autres erreurs restent signalées. Ces contrôles ne sont pas des NumberSetting persistants.',
      'Replaces only the action that originated request with a message, up to 12 buttons and 4 temporary integer inputs; identifiers must be distinct across the whole panel. The request must belong to the context’s world and generation. Each text is limited to 256 UTF-8 bytes without NUL, and each integer value must fall within its inclusive bounds. Clicks return to the same service with the button identifier in action. If the presentation has become stale, for example after signal deletion or a catalogue change, it may be ignored without an exception; a Unit return therefore does not prove that the panel is visible. Other errors are still reported. These controls are not persistent NumberSetting fields.',
    ],
  'native:nimby:fun:ToolContext.showSignalPreview(SignalActionRequest,List<SignalPosition>)': [
    'Publie au plus 64 positions avec le modèle et les propriétés visuelles du signal source, sans construire de signal ; une liste vide retire l’aperçu. Chaque position utilise une voie valide, une fraction finie strictement comprise entre 0 et 1 et une direction -1 ou 1 relative à la voie cible. La répétition conserve le côté du source et applique le sens demandé sur cette voie. L’aperçu reste visible pendant l’édition du source, expire après deux secondes sans publication et doit être renouvelé dans onTick. Le retour confirme la publication, pas la visibilité de chaque position selon le cadrage et les couches du jeu.',
    'Publishes up to 64 positions using the source signal’s model and visual properties, without constructing a signal; an empty list clears the preview. Each position uses a valid track, a finite fraction strictly between 0 and 1, and a direction of -1 or 1 relative to the target track. Repetition preserves the source side and applies the requested direction on that track. The preview is visible while editing the source, expires after two seconds without publication, and should be refreshed in onTick. Returning confirms publication, not visibility of every position under the game’s viewport and layer settings.',
  ],
  'native:nimby:fun:ToolContext.createSignals(Long,Long,List<SignalPosition>)': [
    'Répète un signal source avec un ticket non nul obtenu par prepareConstruction et de 1 à 64 positions distinctes par couple voie/fraction. Chaque fraction est finie et strictement comprise entre 0 et 1 ; direction vaut -1 ou 1 sur la voie cible. La copie conserve les propriétés du source et ses réglages persistants, y compris false et les entiers ; les valeurs calculées par prepareNetwork ne deviennent pas des préférences copiées. Les réglages sont capturés avant la première création. Vérifier state, reason et createdIds : Partial peut contenir tous les signaux demandés si la copie des réglages a échoué. En cas de Pending, interroger pollConstruction avec le même ticket sans refaire createSignals, car la pose peut déjà avoir eu lieu.',
    'Repeats a source signal using a nonzero ticket obtained from prepareConstruction and 1 to 64 positions distinct by track/fraction pair. Every fraction must be finite and strictly between 0 and 1; direction is -1 or 1 on the target track. Copying preserves source properties and persistent settings, including false values and integers; values calculated by prepareNetwork do not become copied preferences. Settings are captured before the first creation. Check state, reason and createdIds: Partial can contain every requested signal if settings copying failed. For Pending, call pollConstruction with the same ticket without repeating createSignals, because placement may already have occurred.',
  ],
  'jvm:fr.nimby.sdk:fun:NimbyClient.createSignals(Long,Long,List<Position>)': [
    'Répète le signal source avec un ticket non nul préparé par prepareConstruction et de 1 à 64 positions, via le service de construction expérimental. Les couples voie/fraction doivent être distincts ; les fractions sont finies et strictement comprises entre 0 et 1, les directions valent -1 ou 1 sur la voie cible. Les propriétés et réglages persistants du source sont copiés, y compris les valeurs false et les entiers, mais pas les réglages effectifs calculés pour le réseau. Vérifier le résultat : PARTIAL peut signaler un échec de copie des réglages même si toutes les créations sont présentes. Pour PENDING, utiliser pollConstruction avec le même token ; relancer la création peut produire des doublons.',
    'Repeats the source signal with a nonzero ticket prepared by prepareConstruction and 1 to 64 positions, through the experimental construction service. Track/fraction pairs must be distinct; fractions must be finite and strictly between 0 and 1, and directions must be -1 or 1 on the target track. Source properties and persistent settings are copied, including false values and integers, but effective settings calculated for the network are not. Check the result: PARTIAL can report a settings-copy failure even when all creations are present. For PENDING, use pollConstruction with the same token; repeating creation may produce duplicates.',
  ],
  'jvm:fr.nimby.sdk:fun:Game.Construction.create(Long,Long,List<Position>)': [
    'Délègue à NimbyClient.createSignals pour répéter un signal avec le ticket obtenu par construction.prepare. Fournir de 1 à 64 positions distinctes par voie/fraction, avec une fraction finie strictement entre 0 et 1 et une direction -1 ou 1 relative à la voie cible. La répétition conserve les réglages persistants et les propriétés du source, pas les réglages temporaires dérivés par les règles du réseau. Le nombre de createdIds ne suffit pas à confirmer le succès : contrôler state et reason. Si le résultat est PENDING, utiliser construction.poll sur le même token sans créer de nouveau lot.',
    'Delegates to NimbyClient.createSignals to repeat a signal using the ticket obtained from construction.prepare. Supply 1 to 64 positions distinct by track/fraction, with finite fractions strictly between 0 and 1 and directions of -1 or 1 relative to each target track. Repetition preserves source properties and persistent settings, not temporary settings derived by network rules. The number of createdIds alone does not confirm success: inspect state and reason. For a PENDING result, use construction.poll on the same token without creating another batch.',
  ],
  'native:nimby:class:ConstructionResult': [
    'Compte rendu d’une préparation, création, annulation ou interrogation, avec son état, son ticket, les identités créées, un motif et la disponibilité d’une annulation. Lire ces informations ensemble : toutes les identités demandées peuvent être présentes alors que state vaut Partial à cause d’un échec de copie des réglages. Pending signifie que le résultat définitif doit être interrogé avec le même ticket ; ce n’est pas une invitation à refaire la création.',
    'Report from preparation, creation, undo or polling, containing its state, ticket, created identities, reason and undo availability. Read these together: every requested identity can be present while state is Partial because settings copying failed. Pending means the final result must be polled with the same ticket; it is not an invitation to repeat creation.',
  ],
  'jvm:fr.nimby.sdk:class:ConstructionResult': [
    'Compte rendu d’une opération de construction : état, token, identités créées, motif et disponibilité d’une annulation. Contrôler state et reason même si createdIds contient autant d’éléments que demandé : PARTIAL peut indiquer que les signaux ont été créés mais que la copie de leurs réglages a échoué. PENDING demande une interrogation avec le même token, sans soumettre de nouveau lot.',
    'Construction operation report: state, token, created identities, reason and undo availability. Inspect state and reason even when createdIds contains as many entries as requested: PARTIAL may mean that the signals were created but their settings could not be copied. PENDING requires polling with the same token, without submitting another batch.',
  ],
  'native:nimby:val:ConstructionResult.state': [
    'État de l’opération, à contrôler avant de présenter un succès. Applied confirme le lot complet sans motif d’échec ; Partial signale un résultat incomplet ou une copie de réglages échouée, même lorsque toutes les créations ont eu lieu. Pending laisse le résultat en attente et impose une interrogation avec le même ticket. Le seul nombre d’identités créées ne remplace jamais cet état.',
    'Operation state, which must be checked before reporting success. Applied confirms the complete batch without a failure reason; Partial reports an incomplete result or failed settings copying, even when every creation took place. Pending leaves the result unresolved and requires polling with the same ticket. The count of created identities never replaces this state.',
  ],
  'jvm:fr.nimby.sdk:val:ConstructionResult.state': [
    'État de l’opération : APPLIED confirme le lot complet sans motif d’échec ; PARTIAL inclut notamment le cas où toutes les créations existent mais où leurs réglages n’ont pas pu être copiés. PENDING impose de poursuivre avec pollConstruction sur le même token. Ne pas déduire le succès du seul nombre de createdIds.',
    'Operation state: APPLIED confirms the complete batch without a failure reason; PARTIAL includes the case where all creations exist but their settings could not be copied. PENDING requires continued polling with pollConstruction on the same token. Do not infer success solely from the createdIds count.',
  ],
  'native:nimby:val:ConstructionResult.token': [
    'Ticket opaque de l’opération, à conserver pour pollConstruction et, si disponible, undoConstruction. Il ne désigne pas un signal et ne doit pas être recalculé ni réutilisé comme nouvelle autorisation de pose. Lorsque state vaut Pending, poursuivre le suivi avec ce même ticket afin d’éviter une seconde création.',
    'Opaque operation ticket, retained for pollConstruction and, when available, undoConstruction. It is not a signal identity and must not be recomputed or reused as a new placement authorisation. When state is Pending, continue tracking with this same ticket to avoid a second creation.',
  ],
  'jvm:fr.nimby.sdk:val:ConstructionResult.token': [
    'Ticket opaque transmis aux opérations de suivi et d’annulation. Il identifie l’opération préparée et n’est pas une identité de signal. Conserver le même token lorsqu’un résultat reste PENDING ; une nouvelle préparation et une nouvelle création ne constituent pas un moyen sûr d’en connaître l’issue.',
    'Opaque ticket passed to polling and undo operations. It identifies the prepared operation and is not a signal identity. Keep the same token while a result is PENDING; preparing and creating again is not a safe way to discover the previous outcome.',
  ],
  'native:nimby:val:ConstructionResult.createdIds': [
    'Identités des signaux dont la création a été rapportée, et non liste des positions seulement demandées. Elles permettent de rendre compte d’une création partielle. Une liste aussi longue que le lot demandé ne prouve pas que les réglages ont été copiés : examiner aussi state et reason, en particulier Partial avec le motif 7.',
    'Identities of signals whose creation was reported, not a list of positions merely requested. They allow a partial creation to be reported accurately. A list as long as the requested batch does not prove that settings were copied: also inspect state and reason, especially Partial with reason 7.',
  ],
  'jvm:fr.nimby.sdk:val:ConstructionResult.createdIds': [
    'Identités des créations rapportées par le jeu. Elles décrivent les objets obtenus, sans garantir à elles seules la réussite de la copie des réglages. PARTIAL peut donc fournir autant d’identités que demandé ; consulter également reason et canUndo avant de proposer une récupération à l’utilisateur.',
    'Identities of creations reported by the game. They describe the resulting objects without independently guaranteeing successful settings copying. PARTIAL may therefore supply as many identities as requested; also inspect reason and canUndo before offering recovery to the user.',
  ],
  'native:nimby:val:ConstructionResult.reason': [
    'Motif numérique à interpréter avec state ; 0 signifie qu’aucun motif d’échec n’a été rapporté. Le motif 7 indique que la copie des réglages NRF du signal source n’a pas pu être assurée. Il peut accompagner un refus avant création ou un résultat Partial après création : examiner createdIds et ne pas relancer automatiquement la pose.',
    'Numeric reason to interpret together with state; 0 means that no failure reason was reported. Reason 7 indicates that copying the source signal’s NRF settings could not be ensured. It can accompany rejection before creation or Partial after creation: inspect createdIds and do not automatically repeat placement.',
  ],
  'jvm:fr.nimby.sdk:val:ConstructionResult.reason': [
    'Motif numérique associé à l’état ; 0 signifie qu’aucun motif d’échec n’a été rapporté. Le motif 7 concerne l’indisponibilité ou l’échec de la copie des réglages NRF. Un refus peut survenir avant toute création, ou PARTIAL après des créations effectives. Lire createdIds avant de décider de la suite, sans réessayer la pose automatiquement.',
    'Numeric reason associated with the state; 0 means that no failure reason was reported. Reason 7 concerns unavailable or failed copying of NRF settings. Rejection can occur before creation, or PARTIAL after actual creations. Read createdIds before choosing the next action, without automatically retrying placement.',
  ],
  'native:nimby:val:ConstructionResult.canUndo': [
    'Indique si l’annulation de cette opération est disponible au moment du résultat, notamment pour récupérer un lot Partial. true n’est pas une garantie permanente : une autre commande du jeu peut changer l’historique avant undoConstruction. Proposer l’annulation avec le ticket associé puis vérifier son résultat, sans supprimer soi-même les identités rapportées.',
    'Indicates whether undo is available for this operation when the result is produced, including recovery of a Partial batch. true is not a permanent guarantee: another game command may change history before undoConstruction. Offer undo using the associated ticket and check its result rather than deleting the reported identities yourself.',
  ],
  'jvm:fr.nimby.sdk:val:ConstructionResult.canUndo': [
    'Disponibilité d’une annulation pour le token au moment où ce résultat est établi. Elle permet notamment de proposer la récupération d’un lot PARTIAL, mais une commande ultérieure peut rendre l’annulation indisponible. Appeler undoConstruction ou construction.undo puis vérifier le nouvel état au lieu de considérer le booléen comme une garantie définitive.',
    'Undo availability for the token when this result is produced. It can support recovery of a PARTIAL batch, but a later command may make undo unavailable. Call undoConstruction or construction.undo and inspect the new state instead of treating this boolean as a permanent guarantee.',
  ],
  'native:nimby:enum-entry:ConstructionState.Partial': [
    'Des signaux ont été créés, mais le lot n’a pas entièrement réussi. Cela inclut une copie de réglages échouée après toutes les créations : createdIds peut alors contenir le nombre total demandé et reason vaut 7. Présenter les créations rapportées et, si canUndo le permet, proposer une annulation. Ne pas relancer automatiquement createSignals.',
    'Signals were created, but the batch did not fully succeed. This includes failed settings copying after every creation: createdIds may then contain the entire requested count and reason is 7. Report the known creations and offer undo if canUndo permits it. Do not automatically repeat createSignals.',
  ],
  'jvm:fr.nimby.sdk:enum-entry:ConstructionState.PARTIAL': [
    'Le lot a produit des créations sans confirmer un succès complet. Un échec de copie des réglages peut donner cet état alors que tous les signaux demandés ont été créés, avec reason = 7. Utiliser createdIds pour informer l’utilisateur et canUndo pour proposer une récupération ; ne pas soumettre de nouveau lot automatiquement.',
    'The batch produced creations without confirming complete success. A settings-copy failure can produce this state even when all requested signals were created, with reason = 7. Use createdIds to inform the user and canUndo to offer recovery; do not automatically submit another batch.',
  ],
  'native:nimby:enum-entry:ConstructionState.Applied': [
    'Le nombre de créations rapportées correspond au lot demandé et aucun motif d’échec n’a été signalé, y compris lors de la prise en charge de la copie des réglages. La reconnaissance des nouveaux signaux dans une observation ultérieure peut encore être nécessaire pour y retrouver les valeurs copiées. Pour annuler, utiliser le ticket et vérifier canUndo puis le résultat de l’annulation.',
    'The reported creation count matches the requested batch and no failure reason was reported, including when accepting settings copying. Recognition of the new signals in a later observation may still be needed before copied values are available on them. To undo, use the ticket and check canUndo and then the undo result.',
  ],
  'jvm:fr.nimby.sdk:enum-entry:ConstructionState.APPLIED': [
    'Le lot demandé est créé sans motif d’échec rapporté. La copie des réglages a été prise en charge ; leur rattachement aux nouveaux signaux suit leur apparition dans les observations. Cet état n’accorde pas un droit d’annulation permanent : utiliser canUndo et vérifier le résultat d’undo avec le même token.',
    'The requested batch was created without a reported failure reason. Settings copying has been accepted; associating those settings with new signals follows their appearance in observations. This state does not provide a permanent right to undo: use canUndo and check the undo result with the same token.',
  ],
  'native:nimby:enum-entry:ConstructionState.Pending': [
    'L’issue définitive de l’opération n’est pas encore confirmée. Continuer avec pollConstruction et le ticket existant. La création peut déjà avoir commencé ou abouti ; relancer createSignals pour obtenir une réponse plus claire risquerait de poser le lot une seconde fois.',
    'The operation’s final outcome is not yet confirmed. Continue with pollConstruction and the existing ticket. Creation may already have started or completed; repeating createSignals to obtain a clearer response could place the batch a second time.',
  ],
  'jvm:fr.nimby.sdk:enum-entry:ConstructionState.PENDING': [
    'Résultat encore incertain ou en attente. Interroger pollConstruction ou construction.poll avec le token existant. Ne pas recommencer prepare puis create : une réponse en attente peut masquer une création déjà effectuée et le nouvel envoi peut produire des doublons.',
    'The result is still uncertain or pending. Call pollConstruction or construction.poll with the existing token. Do not repeat prepare followed by create: a pending response may hide a creation that already occurred, and submitting again can produce duplicates.',
  ],
}
