/** Public contracts reviewed against Kotlin declarations and their decoders.
 * Keys use catalogue identities; shared text is assigned only to explicit IDs.
 * Native/JVM observations deliberately keep their distinct units and lifetimes. */
type Translation = readonly [string, string]
export const apiContracts: Record<string, Translation> = {}
export const apiContractGuides: Record<string, readonly string[]> = {}
const native = 'native:nimby:'
const jvm = 'jvm:fr.nimby.sdk:'
function add(scope: string, key: string, fr: string, en: string) {
  const id = scope + key
  if (apiContracts[id]) throw new Error(`Duplicate data API contract: ${id}`)
  apiContracts[id] = [fr, en]
}
function type(scope: string, name: string, fr: string, en: string, guide: string) {
  add(scope, `class:${name}`, fr, en)
  apiContractGuides[scope + `class:${name}`] = [guide]
}
function fields(scope: string, owner: string, values: Record<string, Translation>) {
  for (const [name, [fr, en]] of Object.entries(values)) add(scope, `val:${owner}.${name}`, fr, en)
}
function entries(scope: string, owner: string, values: Record<string, Translation>) {
  for (const [name, [fr, en]] of Object.entries(values)) add(scope, `enum-entry:${owner}.${name}`, fr, en)
}
function methods(scope: string, values: Record<string, Translation>) {
  for (const [signature, [fr, en]] of Object.entries(values)) add(scope, `fun:${signature}`, fr, en)
}
const opaque: Translation = ['Valeur opaque à comparer et transmettre telle quelle ; ne pas la découper ni la réutiliser dans une autre partie.', 'Opaque value to compare and pass unchanged; do not decode it or reuse it in another game.']
const captured: Translation = ['Horodatage UTC de l’ordinateur, en millisecondes depuis 1970. Il ne mesure pas le temps simulé.', 'Computer UTC timestamp in milliseconds since 1970. It does not measure simulation time.']
const generation: Translation = ['Génération observée de la partie. Invalider les données dérivées lorsqu’elle change, même si la même sauvegarde est rechargée.', 'Observed game generation. Invalidate derived data when it changes, even when reloading the same save.']
const world: Translation = ['Identité du monde observé, à conserver avec sa génération pour identifier la portée des données.', 'Observed world identity; retain it with its generation to identify the scope of the data.']
const speedFallback: Translation = ['Indique une vitesse de secours du jeu. Ce cas laisse la vitesse mesurée inconnue ; il ne prouve pas un arrêt.', 'Indicates a fallback game speed. Measured speed remains unknown in this case; it does not prove a stop.']
const declaredTags: Translation = ['Tags déclarés directement sur cet objet, sans héritage implicite. null : indisponibles ou non demandés ; liste vide : aucun tag déclaré observé.', 'Tags declared directly on this object, without implicit inheritance. null: unavailable or unrequested; empty list: no observed declared tags.']
const predictedUs: Translation = ['Retard d’arrivée estimé par le jeu, en microsecondes signées ; négatif pour une arrivée prévue en avance. null si inconnu. Ce n’est ni l’âge d’une échéance ni une priorité.', 'Game-estimated arrival delay in signed microseconds; negative means predicted early arrival. null when unknown. Neither a deadline’s age nor a priority.']
const predictedSeconds: Translation = ['Même estimation d’arrivée, convertie de microsecondes en secondes ; conserve le signe et null.', 'The same arrival estimate converted from microseconds to seconds; preserves its sign and null.']
const configured: Translation = ['Profil configuré/acheté du train, demandé explicitement. Indépendant du matériel actuel : ses valeurs ne remplacent pas celles qui manquent dans current.', 'Explicitly requested configured/purchased train profile. Independent of current material: its values do not replace missing current values.']
const current: Translation = ['Caractéristiques de la composition actuelle, si observables et demandées. Ne pas les remplacer par le profil configuré.', 'Characteristics of the current composition, when observable and requested. Do not substitute the configured profile.']
const parentAvailable: Translation = ['true : l’information de parent a été observée, y compris l’absence de parent. false : un parent absent reste inconnu.', 'true: parent information was observed, including no parent. false: an absent parent remains unknown.']
const timetableName: Translation = ['Le SDK expose actuellement l’identité de l’horaire, sans résoudre son nom ; null n’est pas un nom vide.', 'The SDK currently exposes timetable identity without resolving its name; null is not an empty name.']
const trainQueryFields: Record<string, Translation> = {
  includeService: ['Demande l’état et le service des trains. Activé par défaut ; les horaires impliquent aussi cette lecture.', 'Requests train state and service. Enabled by default; timetables also imply this read.'],
  includeLocations: ['Demande les données de localisation et leurs gares/voies. Activé par défaut. Les horaires impliquent aussi ces données ; false ne garantit pas leur absence dans une capture couvrante.', 'Requests location data and related stations/tracks. Enabled by default. Timetables also imply these data; false does not guarantee their absence from a covering snapshot.'],
  includeCharacteristics: ['Demande séparément les caractéristiques configurées et actuelles du matériel. Désactivé par défaut.', 'Requests configured and current material characteristics separately. Disabled by default.'],
  includeTimetables: ['Demande affectations et données d’horaires disponibles ; implique le service ainsi que les voies/gares, même si includeLocations vaut false. N’invente ni nom ni passages futurs.', 'Requests available assignments and timetable data; implies service and track/station data even when includeLocations is false. Does not invent names or future passing times.'],
  includeTags: ['Demande les tags des trains et le catalogue des tags/lignes nécessaire aux jointures ; implique includeLines.', 'Requests train tags and the tag/line catalogue needed for joins; implies includeLines.'],
  includePassengers: ['Demande le nombre d’occupants ; indépendant de la capacité du matériel.', 'Requests occupant count; independent of material capacity.'],
  includeLines: ['Demande le catalogue des lignes, y compris celles sans train affecté. Ne demande pas les tags à lui seul.', 'Requests the line catalogue, including lines without assigned trains. Does not request tags by itself.'],
  includeComposition: ['Demande les véhicules ordonnés et les modèles référencés des compositions configurée et actuelle. Les groupes restent facultatifs.', 'Requests ordered vehicles and referenced models for configured and current compositions. The groups remain optional.'],
}
const characteristicsFields: Record<string, Translation> = {
  maximumSpeedMps: ['Limite du matériel en mètres par seconde, optionnelle ; différente de la vitesse mesurée et de la limite de voie.', 'Optional material speed limit in metres per second; distinct from measured speed and track limit.'],
  maximumSpeedKmh: ['maximumSpeedMps multiplié par 3,6 ; null reste null.', 'maximumSpeedMps multiplied by 3.6; null remains null.'],
  lengthM: ['Longueur du matériel en mètres ; null si non prouvée.', 'Material length in metres; null when not established.'],
  emptyMassKg: ['Masse à vide en kilogrammes ; ne représente pas la masse chargée.', 'Empty mass in kilograms; does not represent loaded mass.'],
  passengerCapacity: ['Capacité en voyageurs de ce profil, optionnelle ; différente des occupants actuellement transportés.', 'Optional passenger capacity of this profile; distinct from current occupants.'],
  carCount: ['Nombre de véhicules de ce profil, optionnel ; ne déduire ni capacité ni longueur de ce nombre seul.', 'Optional vehicle count of this profile; do not infer capacity or length from this count alone.'],
  maximumAccelerationMps2: ['Accélération maximale déclarée, en mètres par seconde carrée ; pas une accélération mesurée.', 'Declared maximum acceleration in metres per second squared; not measured acceleration.'],
  powerW: ['Puissance déclarée en watts, optionnelle ; pas une consommation électrique observée.', 'Optional declared power in watts; not observed electrical consumption.'],
  tractiveForceN: ['Force de traction déclarée en newtons, optionnelle.', 'Optional declared tractive force in newtons.'],
  composition: ['Véhicules dans leur ordre observé. null : inconnus ou non demandés ; liste vide : composition observée vide. Les répétitions d’un modèle sont significatives.', 'Vehicles in observed order. null: unknown or unrequested; empty list: observed empty composition. Repeated models are significant.'],
}
for (const scope of [native, jvm]) {
  type(scope, 'TrainQuery', 'Options d’une lecture de trains. Demander uniquement les groupes utiles ; les options sélectionnent des données, pas un sous-ensemble de trains.', 'Options for a train read. Request only the groups you need; options select data, not a subset of trains.', '/lire/trains-observations')
  fields(scope, 'TrainQuery', trainQueryFields)
  for (const [name, fr, en] of [
    ['TrainId', 'train', 'train'], ['LineId', 'ligne', 'line'], ['StationId', 'gare', 'station'],
    ['TrackId', 'voie', 'track'], ['TimetableId', 'horaire', 'timetable'], ['TagId', 'tag', 'tag'], ['VehicleModelId', 'modèle de véhicule', 'vehicle model'],
  ] as const) {
    type(scope, name, `Identifiant typé de ${fr}, copié du jeu. Son type empêche les jointures entre objets différents ; aucune catégorie métier n’est encodée pour le mod.`, `Typed ${en} identity copied from the game. Its type prevents joins between different objects; it encodes no business category for the mod.`, '/lire/trains-observations')
    fields(scope, name, { value: opaque })
  }
  type(scope, 'TimetableShiftId', 'Identité d’un service dans son horaire. La valeur seule n’est pas unique : comparer le couple timetableId et value.', 'Identity of a shift within its timetable. The value alone is not unique: compare timetableId and value together.', '/lire/horaires-trains')
  fields(scope, 'TimetableShiftId', { timetableId: ['Horaire auquel appartient ce service.', 'Timetable to which this shift belongs.'], value: ['Clé opaque du service, unique seulement au sein de timetableId.', 'Opaque shift key, unique only within timetableId.'] })
  type(scope, 'LineType', 'Classification limitée aux lignes de dépôt et aux autres lignes ; aucune catégorie voyageurs/fret n’est déduite.', 'Classification limited to depot lines and other lines; no passenger/freight category is inferred.', '/lire/lignes-et-tags')
  entries(scope, 'LineType', { Depot: ['Ligne identifiée comme dépôt.', 'Line identified as a depot line.'], Other: ['Ligne observée autre que dépôt ; sa catégorie commerciale n’est pas déterminée.', 'Observed non-depot line; its commercial category is not determined.'] })
  type(scope, 'Timetable', 'Horaire identifié depuis l’affectation d’un train. Ce type ne contient pas un programme complet de passages.', 'Timetable identified from a train assignment. This type does not contain a complete passing schedule.', '/lire/horaires-trains')
  fields(scope, 'Timetable', { id: ['Identité de l’horaire observé.', 'Identity of the observed timetable.'], name: timetableName })
  type(scope, 'Tag', 'Libellé de classement. Comparer l’identifiant ; le nom peut changer. Aucun tag ne déclenche une priorité ou une régulation automatique.', 'Classification label. Compare its identity; its name can change. No tag triggers automatic priority or regulation.', '/lire/lignes-et-tags')
  fields(scope, 'Tag', { id: ['Identité du tag, indépendante de son libellé.', 'Tag identity, independent of its label.'], name: ['Nom observé, éventuellement absent ; ne pas l’utiliser comme clé stable.', 'Observed name, possibly absent; do not use it as a stable key.'] })
  type(scope, 'TrainCharacteristics', 'Caractéristiques copiées d’un profil du matériel, en unités SI. Chaque champ peut être inconnu indépendamment des autres ; ni vitesse instantanée, ni priorité.', 'Copied material-profile characteristics in SI units. Each field can be unknown independently; neither current speed nor priority.', '/lire/materiel')
  fields(scope, 'TrainCharacteristics', characteristicsFields)
  type(scope, 'VehicleModel', 'Modèle référencé par une composition. Le catalogue est limité aux modèles observés ; il ne classe pas les trains en voyageurs ou fret.', 'Model referenced by a composition. The catalogue is limited to observed models; it does not classify trains as passenger or freight.', '/lire/materiel')
  fields(scope, 'VehicleModel', { id: ['Identité du modèle de véhicule.', 'Vehicle-model identity.'], code: ['Code observé du modèle, optionnel.', 'Optional observed model code.'], nameEnglish: ['Nom anglais du catalogue ; ne suit pas automatiquement la langue de l’outil.', 'English catalogue name; does not automatically follow the tool language.'], sourceName: ['Nom de la source du modèle rapporté par le catalogue, optionnel.', 'Optional model-source name reported by the catalogue.'] })
  type(scope, 'TrainVehicle', 'Un véhicule à un emplacement précis d’une composition ; plusieurs véhicules peuvent partager le même modèle.', 'A vehicle at a specific position in a composition; several vehicles may share the same model.', '/lire/materiel')
  fields(scope, 'TrainVehicle', { index: ['Position à partir de zéro dans la composition observée.', 'Zero-based position in the observed composition.'], model: ['Modèle associé à ce véhicule ; ses libellés peuvent rester inconnus.', 'Model associated with this vehicle; its labels can remain unknown.'], modelId: ['Identifiant du modèle, identique à model.id.', 'Model identity, equal to model.id.'] })
  type(scope, 'TrainState', 'État de service observé. null signifie indisponible ; Unknown et Other sont des résultats observés, pas une absence de donnée.', 'Observed service state. null means unavailable; Unknown and Other are observed results, not missing data.', '/lire/trains-observations')
  entries(scope, 'TrainState', {
    Unknown: ['Le jeu rapporte un état indéterminé.', 'The game reports an undetermined state.'], Driving: ['État de conduite rapporté ; ne prouve pas une vitesse strictement positive.', 'Reported driving state; does not prove strictly positive speed.'],
    StationStop: ['Arrêt en gare rapporté.', 'Reported station stop.'], TimedStop: ['Arrêt temporisé rapporté.', 'Reported timed stop.'], Depot: ['État de dépôt rapporté.', 'Reported depot state.'],
    DispatchWait: ['Attente de départ/dispatch rapportée.', 'Reported dispatch wait.'], SignalWait: ['Attente de signal rapportée ; ce champ ne décrit pas à lui seul la règle du signal.', 'Reported signal wait; this field alone does not describe the signal rule.'],
    Mothballed: ['Train remisé hors exploitation selon l’état rapporté.', 'Train mothballed according to the reported state.'], NotPresent: ['Train rapporté non présent ; à distinguer d’un objet absent de la capture.', 'Train reported as not present; distinct from an object missing from the snapshot.'], Other: ['État observé non représenté par une autre valeur connue de cette enum.', 'Observed state not represented by another known enum value.'],
  })
  type(scope, 'TrainAlert', 'Alerte observée du train. null signifie indisponible ; None signifie qu’aucune alerte n’est rapportée. Une alerte n’est pas une priorité.', 'Observed train alert. null means unavailable; None means no reported alert. An alert is not a priority.', '/lire/trains-observations')
  entries(scope, 'TrainAlert', {
    None: ['Aucune alerte rapportée.', 'No reported alert.'], LineClosed: ['Ligne fermée rapportée.', 'Reported closed line.'], NoPath: ['Absence de chemin rapportée.', 'Reported missing path.'], InvalidOrders: ['Ordres invalides rapportés.', 'Reported invalid orders.'], Collision: ['Collision rapportée par le jeu.', 'Collision reported by the game.'], SignalWait: ['Alerte d’attente à un signal.', 'Signal-wait alert.'], ScheduleClosed: ['Horaire fermé rapporté.', 'Reported closed schedule.'], DispatchTracksOccupied: ['Voies de dispatch occupées selon le jeu.', 'Dispatch tracks occupied according to the game.'], NoServices: ['Aucun service disponible selon le jeu.', 'No services available according to the game.'], ServicesAlreadyAssigned: ['Services déjà affectés selon le jeu.', 'Services already assigned according to the game.'], Other: ['Autre code d’alerte observé, non représenté par les valeurs connues.', 'Other observed alert code, not represented by known values.'],
  })
}

// Native train copies belong to the supplied ToolContext, never to a JVM connection.
type(native, 'GameInstant', 'Instant UTC du calendrier du jeu, à la microseconde. Années 1 à 9999 ; microsecond vaut de 0 à 999999. Aucune lecture du jeu lors des conversions.', 'UTC instant in the game calendar, at microsecond precision. Years 1 through 9999; microsecond ranges from 0 to 999999. Conversions do not read the game.', '/lire/horaires-trains')
fields(native, 'GameInstant', { utcSeconds: ['Secondes UTC depuis 1970 dans le calendrier du jeu ; peuvent être négatives.', 'UTC seconds since 1970 in the game calendar; may be negative.'], microsecond: ['Fraction de la seconde entre 0 et 999999.', 'Fraction of the second between 0 and 999999.'] })
methods(native, { 'GameInstant.dateTime()': ['Convertit les secondes en date/heure UTC du jeu ; la fraction microsecond n’appartient pas au GameDateTime retourné.', 'Converts seconds into game UTC date/time; the microsecond fraction is not part of the returned GameDateTime.'] })
type(native, 'Station', 'Gare jointe dans une observation de train ou de plan de ligne. Un nom absent ne prouve pas que la gare n’existe pas.', 'Station joined into a train or line-plan observation. A missing name does not prove the station does not exist.', '/lire/trains-observations')
fields(native, 'Station', { id: opaque, stationId: ['Même identité sous le type StationId.', 'The same identity as a StationId.'], name: ['Nom observé ; null si indisponible.', 'Observed name; null when unavailable.'] })
type(native, 'Line', 'Ligne observée dans un service ou le catalogue. Les informations de parent et de tags sont disponibles seulement lorsqu’elles ont été demandées et validées.', 'Line observed in a service or catalogue. Parent and tag information is available only when requested and validated.', '/lire/lignes-et-tags')
fields(native, 'Line', { id: opaque, lineId: ['Même identité sous le type LineId.', 'The same identity as a LineId.'], name: ['Nom observé de la ligne ; null si indisponible.', 'Observed line name; null when unavailable.'], isDepot: ['true : dépôt ; false : autre type observé ; null : classification inconnue.', 'true: depot; false: another observed type; null: unknown classification.'], type: ['Classification dérivée de isDepot : Depot, Other ou null.', 'Classification derived from isDepot: Depot, Other or null.'], parentLineId: ['Identité du parent ; interpréter null avec parentInformationAvailable.', 'Parent identity; interpret null together with parentInformationAvailable.'], parentInformationAvailable: parentAvailable, declaredTags })
type(native, 'TrainPosition', 'Position copiée d’un train sur une voie. La fraction décrit la position longitudinale, pas une distance en mètres ni une réservation.', 'Copied train position on a track. The fraction describes longitudinal position, not a distance in metres or a reservation.', '/lire/voies')
fields(native, 'TrainPosition', { trackId: opaque, track: ['Identité de la voie sous le type TrackId.', 'Track identity as a TrackId.'], fraction: ['Position entre 0 et 1 selon l’origine de la voie.', 'Position between 0 and 1 relative to the track origin.'], direction: ['+1 de A vers B, -1 de B vers A ; null si inconnu.', '+1 from A to B, -1 from B to A; null when unknown.'], station: ['Gare jointe à la voie de position ; null si aucune jointure exploitable.', 'Station joined to the position track; null when no usable join exists.'] })
const assignmentFields: Record<string, Translation> = { scheduleId: ['Identité opaque de l’horaire affecté ; null si indisponible.', 'Opaque assigned timetable identity; null when unavailable.'], shiftId: ['Clé de service dans scheduleId ; ne pas la comparer seule entre horaires.', 'Shift key within scheduleId; do not compare it alone across timetables.'], orderIndex: ['Indice d’ordre observé à partir de zéro ; null si indisponible.', 'Observed zero-based order index; null when unavailable.'], timetable: ['Horaire construit depuis scheduleId, avec son identité seulement ; null si scheduleId manque.', 'Timetable built from scheduleId, with identity only; null if scheduleId is missing.'], shift: ['Identité composée disponible seulement si horaire et clé de service sont connus.', 'Composite identity available only when timetable and shift key are known.'] }
type(native, 'TrainAssignment', 'Affectation observée d’un train à un horaire, un service et un ordre. N’annonce pas un prochain passage calculé.', 'Observed train assignment to a timetable, shift and order. Does not announce a calculated next passing time.', '/lire/horaires-trains')
fields(native, 'TrainAssignment', assignmentFields)
const timeFields: Record<string, Translation> = {
  gameEpochSeconds: ['Origine UTC du calendrier de simulation, en secondes depuis 1970 ; null si inconnue.', 'UTC simulation-calendar origin in seconds since 1970; null when unknown.'],
  gameTimeUs: ['Compteur observé en microsecondes depuis l’origine de simulation ; pas une date Unix.', 'Observed counter in microseconds from the simulation origin; not a Unix date.'],
  arrivalTimeUs: ['Échéance active d’arrivée en microsecondes depuis l’origine de simulation ; optionnelle.', 'Optional active arrival deadline in microseconds from the simulation origin.'],
  departureTimeUs: ['Échéance active de départ en microsecondes depuis l’origine de simulation ; optionnelle.', 'Optional active departure deadline in microseconds from the simulation origin.'],
  arrivalRemainingSeconds: ['Secondes restantes jusqu’à l’échéance d’arrivée ; peuvent être négatives. Ne représentent pas le retard commercial prévu.', 'Seconds remaining to the arrival deadline; may be negative. Not predicted commercial delay.'],
  departureRemainingSeconds: ['Secondes restantes jusqu’à l’échéance de départ, bornées à zéro ; null si inconnues.', 'Seconds remaining to the departure deadline, clamped to zero; null when unknown.'],
  observedAt: ['Compteur observé converti en calendrier UTC du jeu ; null si l’origine ou le compteur manque, ou si la conversion dépasse la plage.', 'Observed counter converted to the game UTC calendar; null if origin/counter is missing or conversion is out of range.'],
  arrival: ['Date UTC de l’échéance active d’arrivée. null si la conversion est impossible ; ce n’est pas nécessairement l’horaire commercial.', 'UTC date of the active arrival deadline. null if conversion is impossible; not necessarily the commercial timetable.'],
  departure: ['Date UTC de l’échéance active de départ. null si la conversion est impossible ; ce n’est pas nécessairement l’horaire commercial.', 'UTC date of the active departure deadline. null if conversion is impossible; not necessarily the commercial timetable.'],
  dispatchRetry: ['Date UTC de nouvelle tentative de dispatch ; pas une heure commerciale de départ. null si non convertible.', 'UTC dispatch-retry date; not a commercial departure time. null when not convertible.'],
}
const dispatchCounter: Translation = ['Échéance de nouvelle tentative de dispatch, en microsecondes depuis l’origine de simulation.', 'Dispatch-retry deadline in microseconds from the simulation origin.']
const dispatchRemaining: Translation = ['Secondes restantes avant une nouvelle tentative de dispatch, bornées à zéro ; null si inconnues.', 'Seconds remaining before a dispatch retry, clamped to zero; null when unknown.']
type(native, 'TrainServiceTimes', 'Échéances actives et temps restants observés. Une durée peut être disponible sans origine de calendrier. Les conversions conservent null ; aucune date future n’est extrapolée.', 'Observed active deadlines and remaining times. A duration can be available without a calendar origin. Conversions preserve null; no future date is extrapolated.', '/lire/horaires-trains')
fields(native, 'TrainServiceTimes', { ...timeFields, dispatchRetryTimeUs: dispatchCounter, dispatchRetryRemainingSeconds: dispatchRemaining })
type(native, 'TrainService', 'Service observé d’un train, avec état, lieux et échéances indépendamment optionnels. La gare de position, le lieu de service et l’arrêt ciblé ne sont pas interchangeables.', 'Observed train service, with independently optional state, locations and deadlines. Position station, service location and target stop are not interchangeable.', '/lire/trains-observations')
fields(native, 'TrainService', {
  state: ['État de service ; null signifie indisponible, différent de TrainState.Unknown.', 'Service state; null means unavailable, unlike TrainState.Unknown.'], alert: ['Alerte observée, optionnelle ; None est une observation sans alerte.', 'Optional observed alert; None is an observation without an alert.'], hidden: ['Visibilité masquée rapportée par le jeu ; null si inconnue.', 'Hidden visibility reported by the game; null when unknown.'], onNetwork: ['Présence sur le réseau rapportée ; null si inconnue. Ne prouve aucune autorisation de mouvement.', 'Reported network presence; null when unknown. Does not prove movement permission.'],
  locationTrackId: ['Voie du lieu de service observé ; peut différer de la voie de position.', 'Track of the observed service location; may differ from the position track.'], locationStation: ['Gare du lieu de service observé ; absence de jointure ne prouve pas l’absence de gare.', 'Station of the observed service location; a missing join does not prove no station exists.'], line: ['Ligne du service ; null si indisponible.', 'Service line; null when unavailable.'], stopTrackId: ['Voie de l’arrêt actuellement ciblé ; null si inconnue.', 'Track of the currently targeted stop; null when unknown.'], stopStation: ['Gare de l’arrêt ciblé, si résolue.', 'Station of the target stop, when resolved.'], stopIndex: ['Indice de l’arrêt courant dans la ligne, à partir de zéro ; null si inconnu.', 'Zero-based current stop index in the line; null when unknown.'], times: ['Échéances du service ; chaque valeur garde sa disponibilité propre.', 'Service deadlines; each value retains its own availability.'],
})
type(native, 'Train', 'Fiche copiée d’un train. Les groupes de TrainQuery déterminent les données optionnelles ; les données inconnues restent null, sans lecture implicite.', 'Copied train record. TrainQuery groups determine optional data; unknown values remain null, without implicit reads.', '/lire/trains-observations')
fields(native, 'Train', { id: opaque, trainId: ['Même identité sous le type TrainId.', 'The same identity as a TrainId.'], name: ['Nom du train dans cette observation ; ne remplace pas son identité.', 'Train name in this observation; does not replace its identity.'], position: ['Position copiée si observable ; null si absente ou indisponible.', 'Copied position when observable; null when absent or unavailable.'], speedMps: ['Vitesse mesurée en mètres par seconde ; null si inconnue ou remplacée par une valeur de secours.', 'Measured speed in metres per second; null when unknown or replaced with a fallback.'], speedKmh: ['Vitesse mesurée convertie en km/h ; null reste null.', 'Measured speed converted to km/h; null remains null.'], speedDefaulted: speedFallback, passengers: ['Occupants observés, seulement si demandés ; null ne vaut pas zéro.', 'Observed occupants, only when requested; null does not mean zero.'], assignment: ['Affectation observée ; null si indisponible ou non demandée.', 'Observed assignment; null when unavailable or unrequested.'], service: ['Service observé, éventuellement partiel : une lecture de localisation peut fournir présence et lieux sans état de service. Les options du callback peuvent aussi avoir été cumulées. null indique qu’aucune partie utilisable n’a été fournie.', 'Observed service, possibly partial: a location read can supply presence and places without service state. Callback options may also have accumulated. null indicates that no usable part was supplied.'], declaredTags, predictedArrivalDelayUs: predictedUs, predictedArrivalDelaySeconds: predictedSeconds, configured, current })
type(native, 'TrainSnapshot', 'Copie de trains obtenue par ToolContext.trains. Conservable après le callback ; les recherches lisent uniquement cette copie. Valide les données séparément, sans figer un tick de simulation.', 'Train copy obtained from ToolContext.trains. Retainable after the callback; lookups read only this copy. Data is validated separately without freezing a simulation tick.', '/lire/trains-observations')
fields(native, 'TrainSnapshot', { worldId: world, generation, capturedAtMillis: captured, ageMillis: ['Âge monotone de la capture au moment de la copie, en millisecondes ; ne se met pas à jour ensuite.', 'Monotonic snapshot age when copied, in milliseconds; does not update afterwards.'], clock: ['Horloge simulée observée ; null si indisponible.', 'Observed simulation clock; null when unavailable.'], trains: ['Trains copiés selon la requête ; leurs champs facultatifs reflètent les groupes demandés.', 'Trains copied according to the query; optional fields reflect requested groups.'], vehicleModels: ['Modèles référencés par les compositions demandées ; null si non demandés ou indisponibles.', 'Models referenced by requested compositions; null when unrequested or unavailable.'], lines: ['Catalogue des lignes demandé, même sans train affecté ; null si inconnu ou non demandé.', 'Requested line catalogue, including lines without assigned trains; null when unknown or unrequested.'], tags: ['Catalogue de tags demandé ; null si inconnu ou non demandé.', 'Requested tag catalogue; null when unknown or unrequested.'] })
methods(native, { 'TrainSnapshot.get(Long)': ['Recherche indexée dans les trains copiés ; null si cet identifiant n’y figure pas. Aucune nouvelle observation.', 'Indexed lookup in copied trains; null if the identity is absent. No new observation.'], 'TrainSnapshot.get(TrainId)': ['Même recherche locale avec un identifiant typé ; null si absent de cette capture.', 'The same local lookup with a typed identity; null when absent from this snapshot.'], 'TrainSnapshot.line(LineId)': ['Ligne du catalogue copié ; null si absente, indisponible ou non demandée.', 'Line from the copied catalogue; null when absent, unavailable or unrequested.'], 'TrainSnapshot.tag(TagId)': ['Tag du catalogue copié ; null si absent, indisponible ou non demandé.', 'Tag from the copied catalogue; null when absent, unavailable or unrequested.'], 'TrainSnapshot.tagsForLine(LineId)': ['Réunit les tags déclarés de la ligne et de ses parents, sans doublons. null si un maillon est inconnu, cyclique ou hors limites ; liste vide seulement pour un héritage connu sans tag.', 'Combines declared tags from the line and its parents without duplicates. null if a link is unknown, cyclic or out of bounds; empty list only for known inheritance without tags.'] })
const stopOffsets: Record<string, Translation> = { index: ['Indice d’arrêt à partir de zéro dans le plan de ligne.', 'Zero-based stop index in the line plan.'], arrivalOffsetSeconds: ['Offset d’arrivée en secondes depuis l’origine du plan ; null si inconnu. Pas une date absolue du train.', 'Arrival offset in seconds from the plan origin; null when unknown. Not an absolute train date.'], departureOffsetSeconds: ['Offset de départ en secondes depuis l’origine du plan ; null si inconnu.', 'Departure offset in seconds from the plan origin; null when unknown.'], plannedDwellSeconds: ['departureOffsetSeconds moins arrivalOffsetSeconds, en secondes ; null si un offset manque.', 'departureOffsetSeconds minus arrivalOffsetSeconds, in seconds; null if either offset is missing.'] }
type(native, 'Stop', 'Arrêt ou waypoint du plan de ligne. Peut être hors gare ; les offsets restent relatifs au plan.', 'Stop or waypoint in a line plan. May be outside a station; offsets remain relative to the plan.', '/lire/horaires-trains')
fields(native, 'Stop', { ...stopOffsets, trackId: opaque, track: ['Identité typée de la voie de l’arrêt.', 'Typed identity of the stop track.'], station: ['Gare jointe, si disponible ; un waypoint peut être hors gare.', 'Joined station, when available; a waypoint can be outside stations.'] })
type(native, 'LinePlan', 'Plan complet de la ligne associée au train dans cette capture, obtenu par ToolContext.linePlan. Peut contenir des arrêts hors de la course partielle du train.', 'Complete plan of the line associated with the train in this snapshot, obtained from ToolContext.linePlan. May contain stops outside the train’s partial run.', '/lire/horaires-trains')
fields(native, 'LinePlan', { trainId: opaque, train: ['Identité typée du train qui a servi à demander ce plan.', 'Typed identity of the train used to request this plan.'], line: ['Ligne observée associée au train.', 'Observed line associated with the train.'], stops: ['Arrêts du plan complet, dans leur ordre ; ne pas les convertir directement en prochains passages du train.', 'Stops in the full plan, in order; do not convert them directly into the train’s next passing times.'], worldId: world, generation, capturedAtMillis: captured })
for (const [alias, target] of [['TrainObservation', 'Train'], ['TrainLine', 'Line'], ['TrainStation', 'Station'], ['TrainLineStop', 'Stop'], ['TrainLinePlan', 'LinePlan']]) {
  add(native, `typealias:${alias}`, `Autre nom du type ${target}, avec les mêmes propriétés et contrats ; aucune copie ou conversion supplémentaire.`, `Another name for ${target}, with the same properties and contracts; no additional copy or conversion.`)
  apiContractGuides[native + `typealias:${alias}`] = ['/lire/trains-observations']
}

// JVM: start with Game's grouped operations; keep detailed APIs discoverable.
add(jvm, 'object:Nimby', 'Point d’entrée d’une application JVM : découvrir les jeux puis ouvrir explicitement une connexion. Un mod Native utilise le contexte fourni par le SDK.', 'JVM application entry point: discover games, then explicitly open a connection. A Native mod uses its SDK-provided context.')
apiContractGuides[jvm + 'object:Nimby'] = ['/lire/connexion']
type(jvm, 'Game', 'Connexion possédée par l’application, regroupée par usage. Utiliser use pour la fermer ; les observations copiées restent lisibles après fermeture. Ne pas construire ce type directement.', 'Application-owned connection grouped by purpose. Use use to close it; copied observations remain readable after closing. Do not construct this type directly.', '/lire/connexion')
fields(jvm, 'Game', { advanced: ['Client détaillé de cette même connexion ; ne pas le fermer séparément.', 'Detailed client for this same connection; do not close it separately.'], trains: ['Lectures ciblées et requêtes de trains.', 'Targeted reads and train queries.'], clock: ['Lecture et changement explicite de la date du jeu.', 'Game-clock reads and explicit date changes.'], signals: ['Essais visuels temporaires de textures de signaux.', 'Temporary visual tests of signal textures.'], mods: ['Statut et sessions temporaires de contrôle des mods chargés.', 'Status and temporary control sessions for loaded mods.'], construction: ['Préparation, création, suivi et annulation de séries expérimentales de signaux.', 'Preparation, creation, tracking and undo of experimental signal batches.'] })
for (const [name, fr, en, guide] of [
  ['Trains', 'Accès aux lectures de trains de cette connexion.', 'Access to train reads on this connection.', '/lire/trains-observations'],
  ['Clock', 'Accès à l’horloge du jeu de cette connexion.', 'Access to the game clock on this connection.', '/lire/horloge'],
  ['Signals', 'Actions d’affichage uniquement ; ne modifient pas les permissions de mouvement.', 'Display actions only; do not change movement permissions.', '/lire/recettes'],
  ['Mods', 'Contrôle explicite des mods présents dans la partie connectée.', 'Explicit control of mods present in the connected game.', '/lire/recettes'],
  ['Construction', 'Construction expérimentale par tickets ; chaque écriture doit être confirmée et suivie.', 'Experimental ticket-based construction; every write must be confirmed and tracked.', '/lire/construction'],
] as const) type(jvm, `Game.${name}`, `${fr} Obtenir cet objet depuis Game.`, `${en} Obtain this object from Game.`, guide)
const targetedRead: Translation = ['Lit uniquement le train demandé : position, vitesse mesurée et paramètres de conduite. null si absent ou instable ; les autres échecs lèvent une exception. Le résultat copié reste utilisable après fermeture.', 'Reads only the requested train: position, measured speed and driving parameters. null if absent or unstable; other failures throw. The copied result remains usable after closing.']
const fullCapture: Translation = ['Capture les tables du réseau et les observations usuelles. Un train sélectionné ajoute son chemin et son plan de ligne ; il ne filtre pas la liste des trains. Les tables sont copiées sans garantir un tick atomique.', 'Captures network tables and ordinary observations. A selected train adds its path and line plan; it does not filter the train list. Tables are copied without guaranteeing an atomic tick.']
const trainCapture: Translation = ['Capture spécialisée selon TrainQuery, sans topologie complète, signaux, occupations ni réservations. selectedTrain demande en plus son plan et les données de service/horaires ; la liste des trains reste un lot.', 'Specialised TrainQuery capture without full topology, signals, occupations or reservations. selectedTrain additionally requests its plan and service/timetable data; the train list remains a batch.']
const clockRead: Translation = ['Lit l’horloge du jeu sans demander les grandes tables de la carte avec le SDK courant. null si indisponible. Réutiliser snapshot.clock lorsqu’une capture existe déjà.', 'Reads the game clock without requesting large map tables with the current SDK. null when unavailable. Reuse snapshot.clock when a snapshot already exists.']
const clockSet: Translation = ['Change explicitement la date UTC, en secondes entières. Conserve la fraction de seconde. recalculateTrains demande aussi le recalcul des trains, avec interventions possibles. En cas d’échec, relire avant toute nouvelle écriture.', 'Explicitly changes the UTC date in whole seconds. Preserves the subsecond fraction. recalculateTrains also requests train recalculation, with possible interventions. On failure, read again before any new write.']
const textureShow: Translation = ['Affiche l’image déclarée du catalogue pendant 1 000 à 60 000 ms. Identité de signal réelle et chemins non vides requis. Modifie l’apparence seule, jamais les règles ni permissions.', 'Displays the declared catalogue image for 1,000 to 60,000 ms. Requires a real signal identity and nonempty paths. Changes appearance only, never rules or permissions.']
const textureRestore: Translation = ['Retire le remplacement visuel temporaire demandé pour ce signal ; ne réécrit aucune règle du mod.', 'Removes the requested temporary visual override for this signal; does not rewrite mod rules.']
const constructionPrepare: Translation = ['Prépare une série à partir d’un signal source observé et retourne son ticket/état. N’ajoute pas de signal. Revalider le plan confirmé après préparation et avant création.', 'Prepares a batch from an observed source signal and returns its ticket/state. Adds no signal. Revalidate the confirmed plan after preparation and before creation.']
const constructionCreate: Translation = ['Envoie une création unique avec un ticket préparé et 1 à 64 positions distinctes. Fractions strictement entre 0 et 1, sens -1 ou 1. Conserver le ticket et consulter poll après PENDING ou réponse incertaine ; ne pas répéter create.', 'Sends one creation with a prepared ticket and 1 to 64 distinct positions. Fractions strictly between 0 and 1, directions -1 or 1. Keep the ticket and poll after PENDING or an uncertain response; do not repeat create.']
const constructionPoll: Translation = ['Relit l’état du ticket existant sans répéter sa création ou son annulation. Utiliser un ticket non nul de la même partie/session d’édition.', 'Reads the existing ticket state without repeating creation or undo. Use a nonzero ticket from the same game/editing session.']
const constructionUndo: Translation = ['Demande une seule annulation de la série. Peut être refusée si une autre commande a remplacé la dernière opération annulable. Vérifier état et canUndo ; suivre une réponse incertaine avec poll.', 'Requests one batch undo. May be refused if another command replaced the latest undoable operation. Check state and canUndo; follow an uncertain response with poll.']
const controlAcquire: Translation = ['Acquiert un bail explicite de 1 000 à 60 000 ms auprès d’un mod ayant observé la partie. Fermer avec use ; renouvellement et reprises ne sont jamais automatiques.', 'Acquires an explicit 1,000 to 60,000 ms lease from a mod that has observed the game. Close with use; renewal and retries are never automatic.']
const closeConnection: Translation = ['Ferme cette connexion et libère ses ressources. Les copies Kotlin déjà retournées restent valables comme anciennes observations ; aucun nouvel appel sur cette connexion.', 'Closes this connection and releases its resources. Previously returned Kotlin copies remain valid as old observations; do not make further calls on this connection.']
methods(jvm, {
  'Nimby.runningGames()': ['Liste les processus de jeu visibles ; ne choisit aucun jeu et ne garantit pas qu’une connexion réussira.', 'Lists visible game processes; selects none and does not guarantee a connection will succeed.'],
  'Nimby.connect(Path,Int?)': ['Ouvre le SDK indiqué pour le PID choisi. Sans PID, exige exactement un jeu visible. Retourne Game à fermer avec use ; aucune mutation automatique.', 'Opens the specified SDK for the chosen PID. Without a PID, requires exactly one visible game. Returns a Game to close with use; no automatic mutation.'],
  'Game.snapshot(Long?)': fullCapture, 'Game.close()': closeConnection,
  'Game.Trains.read(Long)': targetedRead, 'Game.Trains.read(TrainId)': targetedRead,
  'Game.Trains.snapshot(TrainId?,TrainQuery)': trainCapture,
  'Game.Clock.read()': clockRead, 'Game.Clock.set(Instant,Boolean)': clockSet,
  'Game.Signals.showTexture(Long,String,String,Int)': textureShow, 'Game.Signals.restoreTexture(Long)': textureRestore,
  'Game.Mods.status(String)': ['Interroge une fois le mod chargé dans cette partie. Les compteurs décrivent des forçages temporaires, pas tous les signaux gérés. Une exception n’est pas une preuve d’absence du mod.', 'Queries the mod loaded in this game once. Counts describe temporary overrides, not all managed signals. An exception is not proof the mod is absent.'],
  'Game.Mods.control(String,Int)': controlAcquire,
  'Game.Construction.prepare(Long)': constructionPrepare, 'Game.Construction.create(Long,Long,List<Position>)': constructionCreate,
  'Game.Construction.poll(Long)': constructionPoll, 'Game.Construction.undo(Long)': constructionUndo,
})
type(jvm, 'NimbyClient', 'Client détaillé possédant une connexion ; préférer Game pour les usages courants. Les opérations de cette connexion sont sérialisées. Ouvrir via open et fermer avec use ; ne pas construire directement.', 'Detailed connection-owning client; prefer Game for common uses. Operations on this connection are serialized. Open through open and close with use; do not construct directly.', '/lire/connexion')
methods(jvm, {
  'NimbyClient.Companion.open(Path,Int)': ['Ouvre la bibliothèque SDK donnée pour un PID strictement positif et vérifie sa compatibilité. Ferme les ressources d’ouverture si la connexion échoue.', 'Opens the given SDK library for a strictly positive PID and checks compatibility. Releases opening resources if connection fails.'],
  'NimbyClient.readTrain(Long)': targetedRead, 'NimbyClient.prepareConstruction(Long)': constructionPrepare,
  'NimbyClient.createSignals(Long,Long,List<Position>)': constructionCreate, 'NimbyClient.undoConstruction(Long)': constructionUndo,
  'NimbyClient.pollConstruction(Long)': constructionPoll, 'NimbyClient.readSimulationClock()': clockRead,
  'NimbyClient.capture(Long?)': fullCapture, 'NimbyClient.captureTrainData(Long?,TrainQuery)': trainCapture,
  'NimbyClient.setSimulationDateTime(java.time.Instant,Boolean)': clockSet,
  'NimbyClient.showSignalTextureFor(Long,String,String,Int)': textureShow, 'NimbyClient.restoreSignalTexture(Long)': textureRestore,
  'NimbyClient.modControl(String,ControlRequest)': ['Envoie exactement une demande au mod nommé dans la partie connectée. Préférer Game.mods et ModControlSession qui portent l’identité du bail. Inspecter l’état après un échec avant de choisir une nouvelle mutation.', 'Sends exactly one request to the named mod in the connected game. Prefer Game.mods and ModControlSession, which carry lease identity. Inspect state after failure before choosing a new mutation.'],
  'NimbyClient.acquireModControl(String,Int)': controlAcquire, 'NimbyClient.close()': closeConnection,
})
type(jvm, 'Train', 'Observation de base d’un train dans une capture JVM. Enrichir par snapshot.train(trainId) pour joindre le service, les lieux et les métadonnées de cette même capture.', 'Basic train observation in a JVM snapshot. Use snapshot.train(trainId) to join service, locations and metadata from that same snapshot.', '/lire/trains-observations')
fields(jvm, 'Train', { id: opaque, trainId: ['Même identité sous le type TrainId.', 'The same identity as a TrainId.'], name: ['Nom observé du train ; les renommages ne changent pas son identité.', 'Observed train name; renames do not change its identity.'], position: ['Position observable ; null si non disponible.', 'Observable position; null when unavailable.'], speedKmh: ['Vitesse mesurée en km/h ; null pour une mesure indisponible ou de secours.', 'Measured speed in km/h; null for unavailable or fallback measurements.'], speedDefaulted: speedFallback })
type(jvm, 'Position', 'Position sur une voie : fraction longitudinale et sens. Pour construire, utiliser des identifiants observés et une fraction strictement intérieure à la voie.', 'Position on a track: longitudinal fraction and direction. For construction, use observed identities and a fraction strictly inside the track.', '/lire/voies')
fields(jvm, 'Position', { trackId: opaque, track: ['Même identité sous le type TrackId.', 'The same identity as a TrackId.'], fraction: ['Fraction longitudinale : 0 à l’origine de la voie, 1 à son extrémité. Le sens ne change pas cette origine.', 'Longitudinal fraction: 0 at track origin, 1 at its end. Direction does not change this origin.'], direction: ['Sens observé ; -1 ou 1 requis pour construire. Ne pas déduire une orientation géographique de cette valeur.', 'Observed direction; -1 or 1 required for construction. Do not infer a geographic orientation from this value.'] })
type(jvm, 'Track', 'Voie observée avec son éventuelle gare et sa limite de vitesse. Sa longueur appartient à TrackMetric.', 'Observed track with its possible station and speed limit. Its length belongs to TrackMetric.', '/lire/voies')
fields(jvm, 'Track', { id: opaque, trackId: ['Même identité sous le type TrackId.', 'The same identity as a TrackId.'], stationId: ['Gare associée observée, si disponible.', 'Observed associated station, when available.'], station: ['stationId sous forme typée ; null si aucun identifiant disponible.', 'stationId in typed form; null if no identity is available.'], speedLimitKmh: ['Limite de vitesse de la voie en km/h, distincte de la limite du matériel.', 'Track speed limit in km/h, distinct from the material limit.'] })
type(jvm, 'Station', 'Gare du catalogue copié. L’identité sert aux jointures, le nom à l’affichage.', 'Station from the copied catalogue. Use its identity for joins and its name for display.', '/lire/voies')
fields(jvm, 'Station', { id: opaque, stationId: ['Même identité sous le type StationId.', 'The same identity as a StationId.'], name: ['Nom de gare copié lors de la capture.', 'Station name copied during capture.'] })
type(jvm, 'TrackNode', 'Élément du graphe de voies observé. Les liens peuvent être incomplets ou non réciproques ; ils ne prouvent ni l’état d’une aiguille ni un itinéraire réservé.', 'Element of the observed track graph. Links may be incomplete or non-reciprocal; they prove neither switch state nor a reserved route.', '/lire/voies')
fields(jvm, 'TrackNode', { id: opaque, linkA: ['Lien observé côté A ; null signifie inconnu/absent, pas un heurtoir prouvé.', 'Observed link on side A; null means unknown/absent, not a proven buffer stop.'], linkB: ['Lien observé côté B ; null signifie inconnu/absent, pas un heurtoir prouvé.', 'Observed link on side B; null means unknown/absent, not a proven buffer stop.'], x: ['Coordonnée projetée du jeu ; pas une longitude ni une longueur de voie.', 'Projected game coordinate; not longitude or track length.'], y: ['Coordonnée projetée du jeu ; pas une latitude ni une longueur de voie.', 'Projected game coordinate; not latitude or track length.'] })
type(jvm, 'TrackJunction', 'Raccord observé d’une branche sur une voie principale. Décrit la géométrie de connexion, sans garantir une permission de passage.', 'Observed branch attachment to a main track. Describes connection geometry without guaranteeing passage permission.', '/lire/voies')
fields(jvm, 'TrackJunction', { branchTrackId: ['Identité de la voie de branche.', 'Branch-track identity.'], mainTrackId: ['Identité de la voie principale.', 'Main-track identity.'], fraction: ['Fraction du raccord sur la voie principale.', 'Attachment fraction on the main track.'], mainDirection: ['Sens d’approche du raccord sur la voie principale.', 'Direction approaching the attachment on the main track.'], branchDirection: ['Sens de sortie du raccord sur la branche, sans retournement.', 'Direction leaving the attachment onto the branch, without reversal.'] })
type(jvm, 'TrackUsage', 'Intervalle observé de réservation ou d’occupation selon la table d’origine. Plusieurs intervalles peuvent se chevaucher ; ce n’est pas une permission ni un itinéraire ordonné.', 'Observed reservation or occupation interval, according to its source table. Intervals may overlap; this is neither a permission nor an ordered route.', '/lire/voies')
fields(jvm, 'TrackUsage', { trainId: ['Train associé à cet intervalle.', 'Train associated with this interval.'], trackId: ['Voie portant cet intervalle.', 'Track carrying this interval.'], from: ['Borne inférieure de fraction de voie ; inférieure ou égale à to.', 'Lower track-fraction bound; less than or equal to to.'], to: ['Borne supérieure de fraction de voie ; ne donne pas le sens de circulation.', 'Upper track-fraction bound; does not indicate travel direction.'] })
type(jvm, 'Signal', 'Signal copié avec sa position et les informations d’affichage disponibles. Une image n’est pas une preuve d’autorisation de mouvement.', 'Copied signal with its position and available display information. An image is not proof of movement permission.', '/lire/recettes')
fields(jvm, 'Signal', { id: opaque, position: ['Position observée du signal.', 'Observed signal position.'], kind: ['Code de type rapporté par le jeu ; ne le confondre ni avec l’aspect ni avec une priorité.', 'Kind code reported by the game; do not confuse it with aspect or priority.'], textureState: ['Indice observé d’image, si disponible ; appartient au catalogue du signal.', 'Observed image index, when available; belongs to the signal catalogue.'], specificState: ['État spécifique observé, sous la forme système:état ; null si indisponible.', 'Observed specific state in system:state form; null when unavailable.'], texturePath: ['Chemin d’image observé ; null si indisponible. Ne décrit pas une règle de conduite.', 'Observed image path; null when unavailable. Does not describe a driving rule.'] })
type(jvm, 'Service', 'Données de service copiées. Utiliser state, alertState, hidden, onNetwork et les dates converties pour interpréter les résultats ; les valeurs brutes restent disponibles pour diagnostic.', 'Copied service data. Use state, alertState, hidden, onNetwork and converted dates to interpret results; raw values remain available for diagnostics.', '/lire/trains-observations')
fields(jvm, 'Service', {
  ...timeFields, dispatchTimeUs: dispatchCounter, dispatchRemainingSeconds: dispatchRemaining,
  trainId: opaque, train: ['Identité typée du train de ce service.', 'Typed identity of this service’s train.'], lineName: ['Nom de ligne observé, optionnel.', 'Optional observed line name.'], status: ['Code d’état observé ; préférer la propriété typée state.', 'Observed state code; prefer the typed state property.'], stationId: ['Identité de la gare du lieu de service, si disponible ; distincte de stopStationId.', 'Service-location station identity when available; distinct from stopStationId.'], flags: ['Indicateurs de disponibilité de cet enregistrement. Préférer les propriétés optionnelles et typées pour le code métier.', 'Availability indicators for this record. Prefer optional and typed properties in application logic.'], lineId: ['Identité de la ligne du service, optionnelle.', 'Optional service-line identity.'], line: ['lineId sous forme typée, sans nouvelle lecture.', 'lineId in typed form, without another read.'], stopStationId: ['Identité de la gare de l’arrêt ciblé, optionnelle.', 'Optional target-stop station identity.'], stopIndex: ['Indice d’arrêt courant à partir de zéro ; null si inconnu.', 'Zero-based current stop index; null when unknown.'], motionFlags: ['Indicateurs observés de présence ; préférer hidden et onNetwork.', 'Observed presence indicators; prefer hidden and onNetwork.'], alert: ['Code d’alerte observé ; préférer alertState.', 'Observed alert code; prefer alertState.'], locationTrackId: ['Voie du lieu de service, optionnelle ; distincte de la position géométrique du train.', 'Optional service-location track; distinct from the train’s geometric position.'], stopTrackId: ['Voie de l’arrêt ciblé, optionnelle.', 'Optional target-stop track.'], lineKind: ['Classification brute de ligne ; préférer isDepotLine ou Line.type.', 'Raw line classification; prefer isDepotLine or Line.type.'], state: ['État typé dérivé du code observé ; null reste indisponible, un code non reconnu devient Other.', 'Typed state derived from the observed code; null remains unavailable, an unrecognised code becomes Other.'], alertState: ['Alerte typée dérivée du code observé ; null reste indisponible.', 'Typed alert derived from the observed code; null remains unavailable.'], hidden: ['Présence masquée rapportée, validée indépendamment du service complet ; null si inconnue.', 'Reported hidden presence, validated independently of complete service data; null when unknown.'], onNetwork: ['Présence sur le réseau rapportée, optionnelle ; ne prouve pas une permission.', 'Optional reported network presence; does not prove permission.'], isDepotLine: ['true pour une ligne dépôt, false pour une autre classification connue ; null si classification inconnue.', 'true for a depot line, false for another known classification; null when unknown.'],
})
type(jvm, 'TrainDetails', 'Affectation et occupants copiés selon les groupes demandés. Les propriétés typées ne calculent aucun prochain horaire.', 'Assignment and occupants copied according to requested groups. Typed properties do not calculate a next scheduled time.', '/lire/horaires-trains')
fields(jvm, 'TrainDetails', { ...assignmentFields, trainId: opaque, train: ['Identité typée du train.', 'Typed train identity.'], passengers: ['Occupants observés ; null si inconnus ou non demandés. Ne vaut pas la capacité.', 'Observed occupants; null when unknown or unrequested. Not capacity.'], orderMode: ['Mode d’ordre observé ; préférer isMothballed pour le remisage.', 'Observed order mode; prefer isMothballed for mothballing.'], isMothballed: ['Indique le remisage d’après un mode d’ordre connu ; null si non interprétable.', 'Indicates mothballing from a known order mode; null when uninterpretable.'] })
type(jvm, 'Platform', 'Information de quai associée à une voie. Un nom absent n’implique pas l’absence du quai.', 'Platform information associated with a track. A missing name does not imply an absent platform.', '/lire/voies')
fields(jvm, 'Platform', { trackId: ['Voie observée associée au quai.', 'Observed track associated with the platform.'], stationId: ['Gare associée, si connue.', 'Associated station, when known.'], name: ['Nom observé du quai, optionnel.', 'Optional observed platform name.'] })
type(jvm, 'LineStop', 'Arrêt ou waypoint d’un plan de ligne ; les heures sont des offsets relatifs au plan, pas des dates absolues du train sélectionné.', 'Stop or waypoint in a line plan; times are offsets relative to the plan, not absolute dates for the selected train.', '/lire/horaires-trains')
fields(jvm, 'LineStop', { ...stopOffsets, lineId: opaque, line: ['Identité typée de la ligne.', 'Typed line identity.'], trackId: ['Identité de la voie de l’arrêt.', 'Stop-track identity.'], track: ['Identité typée de la voie.', 'Typed track identity.'], stationId: ['Gare de l’arrêt ; null pour un waypoint hors gare ou une donnée inconnue.', 'Stop station; null for a waypoint outside stations or unknown data.'], station: ['Identité typée de la gare si connue.', 'Typed station identity when known.'] })
add(jvm, 'typealias:Stop', 'Autre nom de LineStop, avec le même contrat d’offsets relatifs.', 'Another name for LineStop, with the same relative-offset contract.')
type(jvm, 'SimulationClock', 'Horloge copiée du calendrier simulé. Combiner origine et compteur avec toInstant ; ne pas la confondre avec l’heure de l’ordinateur.', 'Copied simulation-calendar clock. Combine origin and counter with toInstant; do not confuse it with computer time.', '/lire/horloge')
fields(jvm, 'SimulationClock', { epochSeconds: ['Origine du calendrier du jeu en secondes UTC depuis 1970 ; peut précéder 1970.', 'Game-calendar origin in UTC seconds since 1970; may precede 1970.'], ticks: ['Compteur simulé en centièmes de seconde depuis l’origine ; doit être positif ou nul pour toInstant.', 'Simulation counter in hundredths of a second from the origin; must be nonnegative for toInstant.'] })
methods(jvm, { 'SimulationClock.toInstant()': ['Additionne l’origine et les ticks, en conservant les centièmes. Rejette les ticks négatifs et les dates hors plage ; aucune lecture du jeu.', 'Adds origin and ticks while preserving hundredths. Rejects negative ticks and out-of-range dates; no game read.'] })
type(jvm, 'SimulationTimeChange', 'Résultat d’un changement explicite de date. Contient l’horloge retournée et le nombre d’interventions lors du recalcul demandé.', 'Result of an explicit date change. Contains the returned clock and intervention count for the requested recalculation.', '/lire/horloge')
fields(jvm, 'SimulationTimeChange', { clock: ['Horloge retournée après la commande ; relire plus tard pour un nouvel état.', 'Clock returned after the command; read again later for new state.'], interventions: ['Nombre d’interventions du recalcul ; zéro lorsqu’aucun recalcul n’a été demandé.', 'Recalculation intervention count; zero when no recalculation was requested.'] })

type(jvm, 'Observation', 'Ensemble de valeurs copiées, conservable après fermeture. Son contenu dépend du mode de capture et des groupes demandés. Les jointures locales n’actualisent rien ; une capture ne garantit pas un tick atomique.', 'Set of copied values, retainable after closing. Contents depend on capture mode and requested groups. Local joins refresh nothing; a snapshot does not guarantee an atomic tick.', '/lire/trains-observations')
fields(jvm, 'Observation', {
  capturedAtMillis: captured, processId: ['PID du jeu source de cette capture ; choisir explicitement la partie lors de la connexion.', 'PID of the game supplying this snapshot; explicitly choose the game when connecting.'], gameHash: ['Empreinte du binaire du jeu observé, utile dans un diagnostic de compatibilité ; pas une identité de sauvegarde.', 'Observed game-binary fingerprint, useful for compatibility diagnostics; not a save identity.'],
  trains: ['Observations de base des trains du lot ; selectedTrain ne filtre pas cette liste.', 'Basic observations of trains in the batch; selectedTrain does not filter this list.'], tracks: ['Voies demandées par le mode de capture. Une requête spécialisée sans lieux peut laisser cette liste vide.', 'Tracks requested by capture mode. A specialised query without locations can leave this list empty.'], stations: ['Gares demandées par le mode de capture ; liste vide ne prouve pas un monde sans gares.', 'Stations requested by capture mode; an empty list does not prove a station-free world.'], nodes: ['Graphe observé de la capture complète ; vide dans la capture spécialisée de trains et éventuellement si indisponible.', 'Observed full-capture graph; empty in specialised train captures and possibly when unavailable.'], junctions: ['Raccords observés de la capture complète ; vide dans la capture spécialisée, sans preuve d’absence d’aiguilles.', 'Observed full-capture attachments; empty in specialised captures without proving there are no junctions.'], signals: ['Signaux observés de la capture complète ; la capture spécialisée de trains ne les demande pas.', 'Observed full-capture signals; specialised train captures do not request them.'],
  services: ['Services demandés et observables ; une liste vide peut aussi résulter d’un groupe non demandé ou indisponible.', 'Requested, observable services; an empty list can also result from an unrequested or unavailable group.'], details: ['Affectations/occupants selon les options de lecture ; interpréter chaque propriété facultative séparément.', 'Assignments/occupants according to read options; interpret each optional property separately.'], platforms: ['Quais de la capture complète, si observables ; non demandés dans la capture spécialisée.', 'Full-capture platforms when observable; not requested in specialised captures.'], reservations: ['Intervalles de réservation, si observables ; null dans une capture spécialisée. Une réservation n’est pas une occupation.', 'Reservation intervals when observable; null in a specialised capture. A reservation is not an occupation.'], occupations: ['Intervalles d’occupation, si observables ; null dans une capture spécialisée. Une table inconnue ne prouve pas une voie libre.', 'Occupation intervals when observable; null in a specialised capture. An unknown table does not prove a clear track.'], selectedPath: ['Chemin du train sélectionné dans une capture complète ; null si non demandé ou indisponible. Pas une permission de passage.', 'Selected train path in a full capture; null when unrequested or unavailable. Not a passage permission.'], lineStops: ['Plan de ligne demandé pour selectedTrain ; null si non demandé ou indisponible. Peut dépasser sa course partielle.', 'Line plan requested for selectedTrain; null when unrequested or unavailable. May extend beyond its partial run.'], clock: ['Horloge simulée copiée avec la capture, si disponible.', 'Simulation clock copied with the snapshot, when available.'], trackMetrics: ['Longueurs observées des voies de la capture complète ; null si non disponibles ou non demandées. Une ligne manquante reste inconnue.', 'Observed full-capture track lengths; null when unavailable or unrequested. A missing row remains unknown.'], lines: ['Catalogue des lignes demandé explicitement ; null si non demandé ou indisponible.', 'Explicitly requested line catalogue; null when unrequested or unavailable.'], tags: ['Catalogue des tags demandé explicitement ; null si non demandé ou indisponible.', 'Explicitly requested tag catalogue; null when unrequested or unavailable.'], trainMetadata: ['Métadonnées enrichies des trains selon TrainQuery ; null hors de cette capture ou si indisponibles.', 'Rich train metadata according to TrainQuery; null outside this capture or when unavailable.'], vehicleModels: ['Modèles référencés par les compositions demandées ; null si non demandés ou indisponibles.', 'Models referenced by requested compositions; null when unrequested or unavailable.'],
})
for (const [name, parameter, fr, en] of [
  ['train', 'Long', 'fiche jointe du train', 'joined train record'], ['train', 'TrainId', 'fiche jointe du train', 'joined train record'],
  ['service', 'Long', 'service du train', 'train service'], ['service', 'TrainId', 'service du train', 'train service'],
  ['details', 'Long', 'fiche d’affectation/occupants du train', 'train assignment/occupant details'], ['details', 'TrainId', 'fiche d’affectation/occupants du train', 'train assignment/occupant details'],
  ['station', 'Long', 'gare', 'station'], ['station', 'StationId', 'gare', 'station'], ['track', 'Long', 'voie', 'track'], ['track', 'TrackId', 'voie', 'track'],
  ['platform', 'Long', 'information de quai pour cette voie', 'platform information for this track'], ['platform', 'TrackId', 'information de quai pour cette voie', 'platform information for this track'],
  ['line', 'LineId', 'ligne du catalogue', 'catalogue line'], ['tag', 'TagId', 'tag du catalogue', 'catalogue tag'], ['metadata', 'TrainId', 'métadonnée enrichie du train', 'rich train metadata'],
]) methods(jvm, { [`Observation.${name}(${parameter})`]: [`Recherche indexée de ${fr} dans cette capture uniquement. null si aucune donnée correspondante ; aucune nouvelle lecture du jeu.`, `Indexed lookup of ${en} in this snapshot only. null if no matching data exists; no new game read.`] })
methods(jvm, { 'Observation.tagsForLine(LineId)': ['Réunit les tags déclarés de la ligne et de ses parents, sans doublons. null si une ligne, un parent ou ses tags sont inconnus, si un cycle apparaît ou si les limites sont dépassées. Ne produit aucune priorité.', 'Combines declared tags of the line and its parents without duplicates. null if a line, parent or tags are unknown, a cycle occurs, or limits are exceeded. Produces no priority.'] })
add(jvm, 'interface:ObservationClient', 'Contrat d’une source d’observations fermable. Utile pour injecter une source contrôlée dans les tests d’une application ; NimbyClient est l’implémentation reliée au jeu.', 'Closeable observation-source contract. Useful for injecting a controlled source into application tests; NimbyClient is the game-connected implementation.')
methods(jvm, { 'ObservationClient.capture(Long?)': fullCapture })
type(jvm, 'GameProcess', 'Processus de jeu découvert. La découverte ne prouve ni qu’une partie est chargée ni que le SDK est compatible.', 'Discovered game process. Discovery proves neither a loaded game nor SDK compatibility.', '/lire/connexion')
fields(jvm, 'GameProcess', { pid: ['Identifiant de processus à passer explicitement à connect.', 'Process identity to pass explicitly to connect.'], executable: ['Chemin de l’exécutable rapporté par le système.', 'Executable path reported by the system.'] })
add(jvm, 'object:GameProcesses', 'Découverte de processus visibles de NIMBY Rails. Préférer Nimby.runningGames au point d’entrée de l’application.', 'Discovery of visible NIMBY Rails processes. Prefer Nimby.runningGames at the application entry point.')
methods(jvm, { 'GameProcesses.discover()': ['Liste les exécutables de jeu reconnus parmi les processus visibles. Retourne une liste vide si aucun n’est visible ; ne sélectionne ni n’ouvre une connexion.', 'Lists recognised game executables among visible processes. Returns an empty list when none is visible; neither selects nor opens a connection.'] })
type(jvm, 'SdkException', 'Échec d’une opération SDK. Conserver message et statut pour le diagnostic ; distinguer d’un résultat optionnel null. Ne pas relancer automatiquement une écriture après exception.', 'SDK operation failure. Retain message and status for diagnostics; distinguish it from an optional null result. Do not automatically repeat a write after an exception.', '/lire/connexion')
fields(jvm, 'SdkException', { status: ['Code du refus : notamment 2 accès impossible, 7 jeu non pris en charge, 8 donnée indisponible, 11 jeu fermé. Conserver les autres codes sans inventer leur signification.', 'Failure code: notably 2 inaccessible process/file, 7 unsupported game, 8 unavailable data, 11 closed game. Retain other codes without inventing their meaning.'] })
type(jvm, 'Line', 'Ligne du catalogue enrichi. Les informations de parent et de tags sont indépendantes du nom ; aucune catégorie commerciale n’est déduite.', 'Line in the rich catalogue. Parent and tag information is independent of its name; no commercial category is inferred.', '/lire/lignes-et-tags')
fields(jvm, 'Line', { id: ['Identité typée de la ligne.', 'Typed line identity.'], name: ['Nom observé, optionnel ; pas une clé de jointure.', 'Optional observed name; not a join key.'], type: ['Depot ou Other quand la classification est connue ; null sinon.', 'Depot or Other when classification is known; null otherwise.'], parentId: ['Identité du parent ; lire parentInformationAvailable avant d’interpréter null.', 'Parent identity; check parentInformationAvailable before interpreting null.'], parentInformationAvailable: parentAvailable, declaredTags })
type(jvm, 'TrainMetadata', 'Métadonnées demandées explicitement pour un train : estimation d’arrivée, tags et profils matériels. Chaque groupe conserve sa disponibilité.', 'Explicitly requested train metadata: arrival estimate, tags and material profiles. Each group retains its availability.', '/lire/trains-observations')
fields(jvm, 'TrainMetadata', { trainId: ['Identité typée du train à joindre dans la même capture.', 'Typed train identity to join within the same snapshot.'], predictedArrivalDelayUs: predictedUs, predictedArrivalDelaySeconds: predictedSeconds, declaredTags, configured, current })
type(jvm, 'TrainRecord', 'Vue jointe d’un train dans une capture. Les enregistrements manquants restent null ; une gare non résolue ne prouve pas un train hors gare.', 'Joined train view within a snapshot. Missing records remain null; an unresolved station does not prove a train is outside stations.', '/lire/trains-observations')
fields(jvm, 'TrainRecord', { train: ['Observation de base du train.', 'Basic train observation.'], service: ['Service joint par identité de train, si disponible.', 'Service joined by train identity, when available.'], details: ['Affectation/occupants joints par identité de train, si disponibles.', 'Assignment/occupants joined by train identity, when available.'], positionStation: ['Gare de la voie de position géométrique, si résolue.', 'Station of the geometric position track, when resolved.'], locationStation: ['Gare du lieu de service, si résolue ; peut différer de positionStation.', 'Service-location station when resolved; may differ from positionStation.'], stopStation: ['Gare de l’arrêt ciblé, si résolue ; pas nécessairement la position actuelle.', 'Target-stop station when resolved; not necessarily current position.'], metadata: ['Métadonnées enrichies du même train, si demandées et disponibles.', 'Rich metadata for the same train, when requested and available.'], line: ['Ligne du service jointe dans le catalogue demandé.', 'Service line joined from the requested catalogue.'] })
type(jvm, 'TrainDynamics', 'Paramètres de conduite d’un profil matériel, en unités SI. Une lecture ciblée retourne ce profil seulement si exploitable ; les valeurs ne sont pas des performances mesurées.', 'Driving parameters of a material profile in SI units. A targeted read returns this profile only when usable; values are not measured performance.', '/lire/materiel')
fields(jvm, 'TrainDynamics', { maxSpeedMps: ['Vitesse maximale du matériel en mètres par seconde.', 'Material maximum speed in metres per second.'], maxAccelerationMps2: ['Accélération maximale déclarée en mètres par seconde carrée.', 'Declared maximum acceleration in metres per second squared.'], serviceBrakingMps2: ['Paramètre de freinage de service en mètres par seconde carrée.', 'Service-braking parameter in metres per second squared.'], emergencyBrakingMps2: ['Paramètre de freinage d’urgence en mètres par seconde carrée.', 'Emergency-braking parameter in metres per second squared.'], tractiveEffortN: ['Effort de traction déclaré en newtons.', 'Declared tractive effort in newtons.'], powerW: ['Puissance déclarée en watts.', 'Declared power in watts.'], emptyMassKg: ['Masse à vide en kilogrammes, pas masse chargée.', 'Empty mass in kilograms, not loaded mass.'], lengthM: ['Longueur déclarée du profil en mètres.', 'Declared profile length in metres.'] })
type(jvm, 'DrivingObservation', 'Résultat d’une lecture ciblée de conduite. Les profils acheté et actuel sont indépendants ; l’intervalle de temps simulé encadre la lecture, sans garantir un tick atomique.', 'Result of a targeted driving read. Purchased and current profiles are independent; the simulation-time interval bounds the read without guaranteeing an atomic tick.', '/lire/trains')
fields(jvm, 'DrivingObservation', { trainId: opaque, sessionGeneration: ['Génération locale à cette connexion ; réinitialiser l’état dérivé après changement et après toute reconnexion.', 'Generation local to this connection; reset derived state after changes and after every reconnection.'], capturedAtMillis: captured, elapsedBeginMillis: ['Temps simulé écoulé au début de la lecture, en millisecondes.', 'Elapsed simulation time at read start, in milliseconds.'], elapsedEndMillis: ['Temps simulé écoulé à la fin de la lecture, en millisecondes.', 'Elapsed simulation time at read end, in milliseconds.'], purchasedDynamics: ['Paramètres du profil acheté/configuré, si disponibles ; ne remplacent pas currentDynamics.', 'Purchased/configured profile parameters when available; do not substitute for currentDynamics.'], currentDynamics: ['Paramètres du profil actuel, si disponibles ; indépendants du profil acheté.', 'Current-profile parameters when available; independent of the purchased profile.'], position: ['Position ciblée observée ; null si inconnue.', 'Observed targeted position; null when unknown.'], speedMps: ['Vitesse mesurée en mètres par seconde ; null si inconnue ou de secours.', 'Measured speed in metres per second; null when unknown or fallback.'], speedDefaulted: speedFallback, motionAvailable: ['Indique si les données de mouvement sont disponibles ; ne remplace pas les disponibilités propres de position et vitesse.', 'Indicates whether motion data is available; does not replace position and speed’s individual availability.'] })
type(jvm, 'TrackMetric', 'Longueur longitudinale observée en mètres : identifiant non nul, longueur finie strictement positive. Convertit localement fractions et mètres ; ne prouve pas une autorisation de construction.', 'Observed longitudinal length in metres: nonzero identity and finite, strictly positive length. Converts fractions and metres locally; does not prove construction permission.', '/lire/voies')
fields(jvm, 'TrackMetric', { trackId: ['Identité de la voie mesurée, non nulle.', 'Nonzero identity of the measured track.'], lengthM: ['Longueur longitudinale en mètres, finie et strictement positive.', 'Longitudinal length in metres, finite and strictly positive.'] })
methods(jvm, { 'TrackMetric.offsetM(Double)': ['Convertit une fraction finie entre 0 et 1 en mètres depuis l’origine de la voie ; argument invalide rejeté.', 'Converts a finite fraction between 0 and 1 to metres from track origin; rejects invalid input.'], 'TrackMetric.fraction(Double)': ['Convertit une distance finie entre 0 et lengthM en fraction ; ne renverse pas le sens.', 'Converts a finite distance between 0 and lengthM to a fraction; does not reverse direction.'], 'TrackMetric.distanceM(Double,Double)': ['Distance absolue en mètres entre deux fractions valides sur cette même voie ; pas une distance d’itinéraire.', 'Absolute distance in metres between two valid fractions on this same track; not a route distance.'], 'TrackMetric.positionAtMetres(Double,TrackDirection)': ['Construit une Position à la distance donnée depuis l’origine, avec le sens choisi. Les limites de construction restent à vérifier séparément.', 'Builds a Position at the given distance from origin with the chosen direction. Construction constraints still require separate checks.'] })
type(jvm, 'TrackDirection', 'Sens longitudinal dans la représentation de la voie, indépendant de son orientation sur la carte.', 'Longitudinal direction in the track representation, independent of its map orientation.', '/lire/voies')
fields(jvm, 'TrackDirection', { nativeValue: ['Valeur +1 pour Forward, -1 pour Backward, utilisable dans Position.direction.', '+1 for Forward, -1 for Backward, usable as Position.direction.'] })
entries(jvm, 'TrackDirection', { Forward: ['Sens des fractions croissantes, de 0 vers 1.', 'Direction of increasing fractions, from 0 towards 1.'], Backward: ['Sens des fractions décroissantes, de 1 vers 0.', 'Direction of decreasing fractions, from 1 towards 0.'] })
type(jvm, 'ConstructionResult', 'Résultat d’une opération de construction expérimentale. Conserver le ticket pour suivre un état PENDING ou une réponse incertaine ; ne jamais répéter la création pour attendre.', 'Result of an experimental construction operation. Retain the ticket to track PENDING or an uncertain response; never repeat creation to wait for completion.', '/lire/construction')
fields(jvm, 'ConstructionResult', { state: ['État courant de l’opération, à traiter explicitement.', 'Current operation state, to handle explicitly.'], token: ['Ticket opaque associé à la partie/session d’édition. Le conserver avant toute écriture et ne pas le réutiliser après changement de partie.', 'Opaque ticket associated with the game/editing session. Retain it before writing and do not reuse it after a game change.'], createdIds: ['Identités des signaux effectivement rapportés comme créés ; conserver aussi en cas de résultat partiel.', 'Identities of signals actually reported as created; retain them for partial results too.'], reason: ['Code de refus ou de résultat à conserver au journal avec le ticket et l’état ; ne pas déduire une réussite du seul code.', 'Refusal/result code to retain in logs with ticket and state; do not infer success from this code alone.'], canUndo: ['Possibilité d’annulation au moment du résultat ; une commande intermédiaire peut l’invalider.', 'Undo availability at result time; an intervening command can invalidate it.'] })
type(jvm, 'ConstructionState', 'Étapes et résultats distincts d’une opération. Un état en attente ou partiel ne doit pas être traité comme une réussite complète.', 'Distinct operation stages and outcomes. Pending or partial states must not be treated as complete success.', '/lire/construction')
entries(jvm, 'ConstructionState', { READY: ['Préparation acceptée ; aucun signal ajouté par cette préparation.', 'Preparation accepted; no signal added by that preparation.'], APPLIED: ['Création appliquée ; lire createdIds et canUndo.', 'Creation applied; read createdIds and canUndo.'], UNDONE: ['Annulation appliquée.', 'Undo applied.'], REJECTED: ['Opération refusée ; lire reason et l’état de la partie avant une autre demande.', 'Operation refused; read reason and game state before another request.'], PARTIAL: ['Résultat partiel ; conserver les identités retournées et examiner la situation, sans renvoyer la série entière.', 'Partial result; retain returned identities and inspect the situation without resending the full batch.'], PENDING: ['Opération encore en attente ; consulter le ticket avec poll.', 'Operation still pending; inspect its ticket with poll.'] })

type(jvm, 'ControlOperation', 'Opérations de contrôle temporaire. Préférer les méthodes de ModControlSession ; les codes d’aspect et indices de case sont définis par le mod ciblé.', 'Temporary control operations. Prefer ModControlSession methods; aspect codes and checkbox indices are defined by the target mod.', '/lire/recettes')
fields(jvm, 'ControlOperation', { code: ['Code de l’opération transmis par le client ; utiliser l’enum, sans fabriquer une valeur numérique.', 'Operation code sent by the client; use the enum without inventing a numeric value.'] })
entries(jvm, 'ControlOperation', {
  Status: ['Lire le statut et les compteurs de forçages du mod.', 'Read mod status and override counts.'], Acquire: ['Acquérir le bail temporaire de contrôle.', 'Acquire the temporary control lease.'], Renew: ['Renouveler explicitement le bail existant.', 'Explicitly renew the existing lease.'], Release: ['Libérer le bail et ses forçages.', 'Release the lease and its overrides.'], ForceSignal: ['Demander un aspect temporaire accepté par le mod.', 'Request a temporary aspect accepted by the mod.'], RestoreSignal: ['Retirer le forçage d’un signal.', 'Remove a signal override.'], Train: ['Demander une contrainte temporaire sur un train.', 'Request a temporary train constraint.'], RestoreTrain: ['Retirer la contrainte temporaire du train.', 'Remove the temporary train constraint.'], Setting: ['Forcer temporairement une case de réglage.', 'Temporarily override a checkbox setting.'], RestoreSetting: ['Retirer le forçage de cette case.', 'Remove that checkbox override.'], Clear: ['Retirer tous les forçages du bail, sans renouvellement automatique.', 'Remove all lease overrides, without automatic renewal.'], ReadSignal: ['Lire la dernière décision évaluée du signal.', 'Read the signal’s latest evaluated decision.'], ReadTrain: ['Lire l’état de la contrainte du train ; pas une permission.', 'Read train-constraint state; not a permission.'],
})
type(jvm, 'TrainControlMode', 'Mode d’une contrainte de recette temporaire. La vitesse doit être finie et positive sauf Stop, qui exige zéro. Les protections du jeu restent applicables.', 'Mode of a temporary test constraint. Speed must be finite and positive except for Stop, which requires zero. Game protections still apply.', '/lire/recettes')
fields(jvm, 'TrainControlMode', { code: ['Code du mode utilisé par le client ; choisir une valeur nommée de l’enum.', 'Mode code used by the client; choose a named enum value.'] })
entries(jvm, 'TrainControlMode', { SpeedLimit: ['Plafond numérique de vitesse, sans demande de marche avec dégagement physique.', 'Numeric speed ceiling without requesting physical-clearance running.'], PhysicalClearance: ['Plafond de vitesse avec contrôle de dégagement physique ; ne promet pas un passage contre toute autre protection.', 'Speed ceiling with physical-clearance checks; does not promise passage against every other protection.'], Stop: ['Contrainte d’arrêt, avec speedMps égal à zéro.', 'Stop constraint, with speedMps equal to zero.'] })
type(jvm, 'TrainControlState', 'État observé d’une contrainte de train. La valeur renvoyée par readTrain.active correspond à cette enum ; aucun état n’est une permission native de mouvement.', 'Observed train-constraint state. readTrain.active corresponds to this enum; no state is a native movement permission.', '/lire/recettes')
entries(jvm, 'TrainControlState', { Absent: ['Aucune contrainte rapportée.', 'No reported constraint.'], AwaitingExit: ['Contrainte en attente de rattachement à sa sortie ; peut aussi signaler une demande pas encore observée comme appliquée.', 'Constraint awaiting its exit binding; can also indicate a request not yet observed as applied.'], Active: ['Contrainte observée active.', 'Constraint observed as active.'], Completed: ['Contrainte observée terminée.', 'Constraint observed as completed.'], Cancelled: ['Contrainte annulée après réinitialisation du trajet.', 'Constraint cancelled after a route reset.'] })
type(jvm, 'ControlRequest', 'Demande détaillée de contrôle. Pour les recettes ordinaires, ModControlSession renseigne owner et generation et fournit les méthodes nommées. Ne pas fabriquer une identité de bail.', 'Detailed control request. For ordinary test scenarios, ModControlSession supplies owner and generation and provides named methods. Do not invent a lease identity.', '/lire/recettes')
fields(jvm, 'ControlRequest', { operation: ['Action demandée ; détermine les champs utiles.', 'Requested action; determines relevant fields.'], owner: ['Identité opaque non nulle du bail pour une mutation ; fournie par la session de contrôle.', 'Nonzero opaque lease identity for mutations; supplied by the control session.'], generation: ['Génération du monde observée par le mod ; doit correspondre au bail.', 'World generation observed by the mod; must match the lease.'], leaseMillis: ['Durée de bail demandée pour Acquire/Renew, de 1 000 à 60 000 ms.', 'Requested lease duration for Acquire/Renew, from 1,000 to 60,000 ms.'], objectId: ['Identité observée du signal ou train ciblé, selon l’opération.', 'Observed identity of the target signal or train, according to the operation.'], exitSignal: ['Signal de sortie associé à la contrainte, ou zéro si aucune sortie explicite n’est fournie.', 'Constraint-associated exit signal, or zero if no explicit exit is supplied.'], speedMps: ['Plafond demandé en m/s : zéro pour Stop, strictement positif pour les autres modes.', 'Requested ceiling in m/s: zero for Stop, strictly positive for other modes.'], mode: ['Mode explicite de la contrainte de train.', 'Explicit train-constraint mode.'], releaseByRear: ['true : libération après passage de la queue à la sortie ; false : après la tête.', 'true: release after the rear passes the exit; false: after the head.'], value: ['Code d’aspect pour ForceSignal ; 0/1 pour Setting. Sa signification dépend de l’opération et du mod.', 'Aspect code for ForceSignal; 0/1 for Setting. Meaning depends on operation and mod.'], settingIndex: ['Indice de case du modèle de signal ciblé ; pas un identifiant universel de réglage.', 'Checkbox index in the target signal model; not a universal setting identity.'] })
type(jvm, 'ControlResponse', 'Réponse du mod à une demande. Les compteurs concernent les forçages temporaires. Les champs active/aspect/reason dépendent de l’opération ; interpréter avec le contrat du mod.', 'Mod response to a request. Counts concern temporary overrides. active/aspect/reason depend on the operation; interpret them using the mod contract.', '/lire/recettes')
fields(jvm, 'ControlResponse', { capabilities: ['Capacités annoncées par le mod ; ne prouve pas qu’une mutation particulière sera acceptée.', 'Capabilities advertised by the mod; does not prove a particular mutation will be accepted.'], generation: ['Génération du monde actuellement observée par le mod.', 'World generation currently observed by the mod.'], remainingMillis: ['Durée restante du bail en millisecondes ; ne se met pas à jour dans cette copie.', 'Remaining lease duration in milliseconds; does not update within this copy.'], signalCount: ['Nombre de forçages de signaux demandés, pas nombre de signaux gérés.', 'Number of requested signal overrides, not managed signal count.'], trainCount: ['Nombre de contraintes temporaires demandées sur les trains.', 'Number of requested temporary train constraints.'], settingCount: ['Nombre de cases temporairement forcées.', 'Number of temporarily overridden checkboxes.'], active: ['Pour ReadTrain : état TrainControlState. Pour ReadSignal : 0 non forcé, 1 forçage demandé, 2 décision observée conforme au forçage. Ne décrit pas une permission.', 'For ReadTrain: TrainControlState. For ReadSignal: 0 not overridden, 1 override requested, 2 observed decision matches the override. Does not describe permission.'], aspect: ['Code d’aspect de la dernière décision lue ; sa signification appartient au modèle du mod.', 'Aspect code of the latest read decision; meaning belongs to the mod model.'], reason: ['Code de raison de la dernière décision lue ; à interpréter avec le mod ciblé.', 'Reason code of the latest read decision; interpret using the target mod.'], speedMps: ['Plafond associé à la contrainte lue, en mètres par seconde ; pas vitesse mesurée du train.', 'Ceiling associated with the read constraint in metres per second; not measured train speed.'], exitSignal: ['Identité de sortie associée à la contrainte rapportée.', 'Exit identity associated with the reported constraint.'], detail: ['Détail textuel renvoyé par le mod ; utile au journal, sans remplacer les champs structurés.', 'Text detail returned by the mod; useful in logs without replacing structured fields.'] })
type(jvm, 'ModControlSession', 'Bail temporaire obtenu avec game.mods.control. Les forçages ne réécrivent pas les réglages sauvegardés. Expiration et fermeture libèrent les surcharges ; aucun renouvellement ni essai automatique.', 'Temporary lease obtained through game.mods.control. Overrides do not rewrite saved settings. Expiration and closing release overlays; no automatic renewal or retries.', '/lire/recettes')
fields(jvm, 'ModControlSession', { modId: ['Identifiant du mod effectivement ciblé par cette session.', 'Identity of the mod actually targeted by this session.'], owner: ['Identité opaque du propriétaire du bail, fournie à l’acquisition.', 'Opaque lease-owner identity supplied on acquisition.'], generation: ['Génération observée lors de l’acquisition ; une autre partie invalide la session.', 'Generation observed at acquisition; another game invalidates the session.'] })
methods(jvm, {
  'ModControlSession.renew(Int)': ['Renouvelle explicitement ce bail pour 1 000 à 60 000 ms ; ne recrée pas un bail expiré silencieusement.', 'Explicitly renews this lease for 1,000 to 60,000 ms; does not silently recreate an expired lease.'],
  'ModControlSession.forceSignal(Long,Int)': ['Demande une indication temporaire sur un signal connu du mod. L’aspect doit être accepté par son modèle ; relire la décision pour constater son application.', 'Requests a temporary indication on a signal known to the mod. Its model must accept the aspect; read the decision again to observe application.'],
  'ModControlSession.restoreSignal(Long)': ['Retire le forçage du signal pour laisser le modèle recalculer sa décision.', 'Removes the signal override so the model can recalculate its decision.'],
  'ModControlSession.setSetting(Long,Int,Boolean)': ['Force une case par son indice dans le modèle du signal, sans modifier sa valeur sauvegardée.', 'Overrides a checkbox by its index in the signal model, without modifying its saved value.'],
  'ModControlSession.restoreSetting(Long,Int)': ['Retire la surcharge temporaire de cette case ; le réglage sauvegardé redevient la source.', 'Removes this checkbox’s temporary override; the saved setting becomes the source again.'],
  'ModControlSession.constrainTrain(Long,Double,TrainControlMode,Long,Boolean)': ['Demande une contrainte temporaire : vitesse finie en m/s, zéro pour Stop et positive sinon. Le train et toute sortie explicite doivent être connus du mod. Relire l’état ; l’acceptation ne prouve pas un mouvement.', 'Requests a temporary constraint: finite speed in m/s, zero for Stop and positive otherwise. The train and any explicit exit must be known to the mod. Read state again; acceptance does not prove movement.'],
  'ModControlSession.restoreTrain(Long)': ['Retire la contrainte temporaire demandée pour ce train.', 'Removes the temporary constraint requested for this train.'],
  'ModControlSession.readSignal(Long)': ['Lit la dernière décision évaluée du signal ; ne force aucune nouvelle évaluation et ne renouvelle pas le bail.', 'Reads the signal’s latest evaluated decision; neither forces a new evaluation nor renews the lease.'],
  'ModControlSession.readTrain(Long)': ['Lit l’état de contrainte du train ; active correspond à TrainControlState, pas à une permission.', 'Reads train-constraint state; active corresponds to TrainControlState, not permission.'],
  'ModControlSession.clear()': ['Retire toutes les surcharges de cette session ; ne remplace pas close pour libérer le bail.', 'Removes all overlays from this session; does not replace close for releasing the lease.'],
  'ModControlSession.close()': ['Demande la libération une seule fois puis ferme la session locale, même si la libération échoue. Aucun appel ensuite ; l’expiration reste le filet de récupération des surcharges.', 'Requests release once, then closes the local session even if release fails. No further calls; expiry remains the override-recovery fallback.'],
})
type(jvm, 'DiagnosticLog', 'Journal applicatif avec rotation et regroupement des messages identiques. Le composant doit être un nom de 1 à 80 caractères alphanumériques, point, tiret ou soulignement, différent de « . » et « .. ». Ne pas journaliser chaque lecture réussie.', 'Application log with rotation and coalescing of identical messages. Component names use 1 to 80 alphanumeric, dot, hyphen or underscore characters, excluding the names “.” and “..”. Do not log every successful read.', '/maintenance/journaux')
fields(jvm, 'DiagnosticLog', { component: ['Nom du composant utilisé dans le dossier et les lignes du journal.', 'Component name used in the directory and log entries.'], directory: ['Dossier du composant sous la racine du journal.', 'Component directory beneath the log root.'], file: ['Fichier du composant et du PID de l’application ; ne contient pas les sauvegardes du jeu.', 'Component/application-PID file; does not contain game saves.'] })
methods(jvm, { 'DiagnosticLog.Companion.defaultRoot()': ['Utilise NRF_LOG_DIR si renseigné ; sinon NimbyRailsFrance/logs sous LOCALAPPDATA, ou le dossier utilisateur si cette variable manque.', 'Uses NRF_LOG_DIR when set; otherwise NimbyRailsFrance/logs under LOCALAPPDATA, or the user directory when that variable is missing.'], 'DiagnosticLog.Companion.forComponent(String)': ['Réutilise le journal du nom donné dans cette application, pour partager le regroupement des répétitions.', 'Reuses the named log in this application so repeated-message coalescing is shared.'], 'DiagnosticLog.write(String,Throwable?,String)': ['Écrit un événement et éventuellement une exception ; regroupe les répétitions identiques pendant 30 secondes. Ferme le fichier après écriture ; une erreur d’écriture est rapportée sur stderr.', 'Writes an event and optionally an exception; coalesces identical repetitions for 30 seconds. Closes the file after writing; write failure is reported to stderr.'], 'DiagnosticLog.startApplication(String)': ['À installer une seule fois au point d’entrée de votre application. Journalise version, erreurs JVM non interceptées et arrêt ; conserve le gestionnaire précédent. N’intercepte pas tous les crashs natifs.', 'Install once at your application entry point. Logs version, uncaught JVM errors and shutdown; preserves the previous handler. Does not intercept every native crash.'] })

// Member links inherit only their explicitly assigned public owner's guide.
for (const id of Object.keys(apiContracts)) {
  if (apiContractGuides[id]) continue
  const prefix = id.startsWith(native) ? native : jvm
  const key = id.slice(prefix.length)
  const qualified = key.slice(key.indexOf(':') + 1).replace(/\(.*/, '')
  const parts = qualified.split('.')
  while (parts.length > 1) {
    parts.pop()
    const guide = apiContractGuides[prefix + 'class:' + parts.join('.')]
    if (guide) { apiContractGuides[id] = guide; break }
  }
}
