import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { execFileSync } from 'node:child_process'
import { captureEdition, digest, serialize, verifySnapshot } from './edition-snapshot.mjs'

const args = process.argv.slice(2)
const option = (name) =>
  args.find((value) => value.startsWith(`--${name}=`))?.slice(name.length + 3)
const directory = resolve('app/content/editions')
mkdirSync(directory, { recursive: true })
const registryPath = resolve(directory, 'registry.json')
let registry
try {
  registry = JSON.parse(readFileSync(registryPath, 'utf8'))
} catch (error) {
  if (error.code !== 'ENOENT') throw error
  registry = { current: '', editions: [] }
}
for (const entry of registry.editions)
  verifySnapshot(entry, readFileSync(resolve(directory, entry.id + '.json'), 'utf8'))
if (args.includes('--check')) {
  if (
    !registry.current ||
    !registry.editions.some((item) => item.id === registry.current && !item.archived)
  )
    throw new Error('No current edition')
  const current = registry.editions.find((item) => item.id === registry.current)
  if (
    serialize(captureEdition(current.id)) !==
    readFileSync(resolve(directory, current.id + '.json'), 'utf8')
  )
    throw new Error('Current edition is stale: run npm run edition:capture')
  console.log(
    `${registry.editions.length} edition snapshots verified; current ${registry.current} matches authoring sources.`,
  )
} else {
  const id = option('id') || registry.current
  if (!/^\d+\.\d+$/.test(id)) throw new Error('Use --id=major.minor')
  const previous = registry.editions.find((item) => item.id === id)
  if (previous?.archived) throw new Error(`Edition ${id} is archived and cannot be overwritten`)
  const commit = option('archive-from')
  if (commit && !/^[0-9a-f]{40}$/.test(commit))
    throw new Error('--archive-from requires a full Git commit')
  const archiveCurrent = args.includes('--archive')
  if (archiveCurrent && !previous) throw new Error('Capture the edition before archiving it')
  if (!previous && !commit && registry.editions.some((item) => !item.archived))
    throw new Error('Archive the current edition before creating a new one')
  const payload = archiveCurrent
    ? readFileSync(resolve(directory, id + '.json'), 'utf8')
    : serialize(captureEdition(id, { commit, sdkCommit: option('sdk-commit') }))
  const snapshot = JSON.parse(payload)
  if (commit && option('sdk-commit')) {
    const sdkCommit = option('sdk-commit')
    if (!/^[0-9a-f]{40}$/.test(sdkCommit))
      throw new Error('--sdk-commit requires a full Git commit')
    const source = (path) =>
      execFileSync('git', ['show', `${sdkCommit}:${path}`], {
        cwd: resolve(option('sdk') || '../sdk'),
        maxBuffer: 16 * 1024 * 1024,
      })
    if (source('VERSION').toString('utf8').trim() !== snapshot.sdkVersion)
      throw new Error('Historical SDK version does not match the archive')
    for (const file of snapshot.provenance.files)
      if (digest(source(file.path)) !== file.sha256)
        throw new Error(`Historical SDK source hash mismatch: ${file.path}`)
  }
  const entry = {
    id,
    sdkVersion: snapshot.sdkVersion,
    archived: Boolean(commit || archiveCurrent),
    sha256: digest(payload),
  }
  if (previous) registry.editions[registry.editions.indexOf(previous)] = entry
  else registry.editions.push(entry)
  if (!entry.archived) registry.current = id
  registry.editions.sort((a, b) => b.id.localeCompare(a.id, 'en', { numeric: true }))
  writeFileSync(resolve(directory, id + '.json'), payload)
  writeFileSync(registryPath, serialize(registry))
  writeFileSync(
    resolve(directory, 'snapshots.ts'),
    '// Generated by scripts/snapshot-edition.mjs. Do not edit.\n' +
      registry.editions
        .map((item, i) => `import snapshot${i} from './${item.id}.json'`)
        .join('\n') +
      '\nexport default {\n' +
      registry.editions.map((item, i) => `  '${item.id}': snapshot${i},`).join('\n') +
      '\n}\n',
  )
  console.log(
    `Captured SDK ${snapshot.sdkVersion} as ${id}${entry.archived ? ' (archived)' : ' (current)'}. Nothing published.`,
  )
}
